Auto stash before merge of "develop" and "origin/develop"

diff --git a/deploy/install/components/remotedesktop.yml b/deploy/install/components/remotedesktop.yml
--- a/deploy/install/components/remotedesktop.yml
+++ b/deploy/install/components/remotedesktop.yml
@@ -24,6 +24,9 @@ component:
             node:
                 private: no
                 public: no
+    parameters:
+        - Username
+        - Password
     install:
         bash:
             wall_time: 15
@@ -31,30 +34,55 @@ component:
                 ###########################################################
                 # Install xfce + tigervnc                                 #
                 ###########################################################
+                case $LINUX_KIND in
+                    centos|redhat)
+                        yum install -y epel-release && \
+                        yum makecache fast && \
+                        yum groupinstall -y -t "X Window system" && \
+                        yum groupinstall -y -t Xfce && \
+                        yum install -y -t perl xorg-x11-fonts-Type1 firefox || exit $?
+                        ;;
+                    debian|ubuntu)
+                        wait_for_apt && apt update && \
+                        wait_for_apt && apt install -y perl xfce4 firefox
 
-                # Configure Xvnc parameters
-                mkdir -p ~cladm/.vnc
-                cat >~cladm/.vnc/xstartup <<-'EOF'
+                        ;;
+                    *)
+                        echo "unsupported OS type '$LINUX_KIND'"
+                        exit 1;;
+                esac
+
+                wget -O tigervnc.tar.gz https://bintray.com/tigervnc/stable/download_file?file_path=tigervnc-1.9.0.x86_64.tar.gz && \
+                tar --strip-components=1 -zxvf tigervnc.tar.gz -C / || exit $?
+                rm -rf tigervnc.tar.gz
+
+                if [ ! -d ~{{.Username}} ]; then
+                    echo "Homedir of user {{.Username}} not found"
+                    exit 100
+                fi
+
+                # Configurations
+                mkdir -p ~{{.Username}}/.vnc
+                cat >~{{.Username}}/.vnc/xstartup <<-'EOF'
                 #!/bin/sh
                 unset SESSION_MANAGER
                 unset DBUS_SESSION_BUS_ADDRESS
                 export DISPLAY=:0
+                cd ~{{.Username}}
                 exec startxfce4
                 EOF
-                chmod u+rx ~cladm/.vnc/xstartup
+                chmod u+rx ~{{.Username}}/.vnc/xstartup
 
-                cat >~cladm/.vnc/config <<-'EOF'
+                cat >~{{.Username}}/.vnc/config <<-'EOF'
                 screen=0 1600x900x24
                 geometry=1600x900
-                desktop={{ .Hostname }}
+                desktop={{.Hostname}}
                 passwordfile=
                 extension=GLX
                 noreset
                 SecurityTypes=None
                 ZlibLevel=0
-                Localhost=no
                 EOF
-                chown -R cladm:cladm ~cladm/.vnc
 
                 cat >/etc/systemd/system/vncserver@:0.service <<'EOF'
                 [Unit]
@@ -66,7 +94,7 @@ component:
                 User={{.Username}}
                 PIDFile=/home/%u/.vnc/%H%i.pid
                 ExecStartPre=/bin/bash -c '/usr/bin/vncserver -kill %i &>/dev/null || :'
-                ExecStart=/usr/bin/vncserver %i -fg -SecurityTypes None -geometry 1600x900  -localhost no --I-KNOW-THIS-IS-INSECURE
+                ExecStart=/usr/bin/vncserver %i -fg -SecurityTypes None
                 ExecStop=/usr/bin/vncserver -kill %i
 
                 [Install]
@@ -80,47 +108,128 @@ component:
 
                 [Service]
                 Type=simple
-                Environment=DISPLAY=%i
                 User={{.Username}}
-                ExecStart=/usr/bin/vncconfig -nowin
+                ExecStart=/usr/bin/vncconfig -display %i -nowin
 
                 [Install]
                 WantedBy=multi-user.target
                 EOF
-                systemctl daemon-reload
 
-                case $LINUX_KIND in
-                    centos|redhat)
-                        yum install -y epel-release && \
-                        yum make-cache fast && \
-                        yum groupinstall -y -t "X Window system" && \
-                        yum groupinstall -y -t Xfce && \
-                        yum install -y -t xorg-x11-fonts-Type1 firefox tigervnc-server && \
-                        systemctl enable vncserver@:0.service && \
-                        systemctl enable vncconfig@:0.service && \
-                        systemctl restart vncserver@:0.service && \
-                        systemctl restart vncconfig@:0.service
+                # Xfce Desktop configurations
+                # to update, from a Desktop configured as wanted:
+                # tar --exclude .config/g* -Jcvf remotedesktop_conf.tar.xz .config
+                # base64 remotedesktop_conf.tar.xz >remotedesktop_conf.tar.xz.encoded
+                # Then copy between EOFs the content of the .encoded file
+                cat >/var/tmp/remotedesktop_conf.tar.xz.encoded <<'EOF'
+                /Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4O//FW9dABcYyecMYYgb8tkd/QwXnBEBYq7o9K5cz3Dw
+                IsSonUkO6IaHvO+YS5nNHN2/lJlax4FCiWhkmwiAJRTWbQy6nFQuCNTNR5RdGaujqV44zxFE5CBR
+                FiN6bl2NP2uZ5T48K9Q83bcLDuMSi1aQGYaj9hyFQp0aO1Emt7tMgDStsEebG1Wm2YSx0d8STDbe
+                fvMe5tltJA5Wg4xplmQ7BuKDmJhmY0IADb0avqPTPDujHgsBEKK6Pt0wxyziiFabjzjyFc5ZI87R
+                qEkK3ZjxKhpFVxPGT5s8XpXrKOGR5nnfUVCu09IFdP21sI19cuAi+9rf9BLJhgYnOBfBIzsKOv+C
+                J1NGBK38NGOiXhByh2jussDoD5+ZnBkjZUuu4SGkEWco+uirn5TOZnmI8KWp/rVs9Y7v9ioJ8jsS
+                Qcfu2BEMUyBQVy2IsAc11y6mw65eLTgGHvy2Gn7prnEU3rAPEFsz0zssRt/2wf6fhcv0zLUrHc7Z
+                CF0p8jOx5BM4E3bV7CyJXoAvfic1TkhFFjRSlK2Dmgq7iX706J2KkVDY7rFL4HlzHk5HdQlHFUoG
+                zrr5rI7cRWTx01z6qJLl6VszVihhXY98SHYXKXqONxhNRWKZpcDWoaS07aThVyZFw6kdu9W0jn8W
+                MBOl1B5C0KvoI0MEO/rX0Nc5EqrygF2Y6gfjKKKDCZtE9q6yEgakrI/lA4TpXKBd1fYSB/khqsCN
+                EZdxpn6e9O7zcfGj61YicL5fAOgCRWQLBjMNk7WkVgLOXaZZsjJZqk0Nx6+SFO4mViaKc2D4Kqlp
+                Xu5V1asUTTC+bZZ4PsHUQsGu4EA5/HJfQmc9aF+eFsVECR6tH5GYGCIEXrfVzl2jzA2rbIeetgVG
+                QY/LKTW0DR8awOhq785HXO0KSbu7J9+XXWfk3ZfphD1xvshOuJrVlvht0Domd2e69/Ce6MsCsJba
+                fXtXQCMmssqYa3vcbdTDYL54nMg+fYf5/6jwtpM8/PA/ucC07PyXZpA3ZRw9Ahvfn5vW8ABaDtAI
+                /950H0ISstVIGr9UIVa9ftjHoQ9gANmBP6Tmrs+USEYuqwC8MFpGDDEdFSn6dkFp8lBRLA7GfXIF
+                A/+VNC+Sma9s8cNLvjn8MoREZwIBbif3YVn03isZ7WLj/6jUWnQDCX/XrL4rFboG9sXY52k3oD5p
+                GdGjNsOlhK3y8X86CNYhcfQMEFP5pE+tvEz/ybTJz4r0pi4QuvaX/6xrfdNGusEp7HsTzflf5xhp
+                3FYtCw2J/XnW+xRY4RGcucUQuix4AtTtxY2oJo20bGGd1K857AbYMqeuf7OorFuJLM2K1REKtXaF
+                QL3h91gs2yWuO7lahFuYAVztpdjVCTe9hGsj3bZmZXtu6S4SXqxbfasYwOKDAcQXagHTuaR6+RH8
+                uYuZeQ3UCnImSWQPWXs8sY/Bibs6jKheQ47W94o7IVb8DlxTJkrJfpR+fe8vUg1fRPBZia8SCy0S
+                h+Ibjql9HF2aRZ10dqbWP5R4Ua/O+rC+A8iiMblcZjIqJrFwBi9O7NljA0ArQt64RMctZDr8syff
+                NhOO1GI3E8fgpAX+tIq2VAkTT4/rY33U1TKK0wcTrHQM35+WKnhUQ4xxH1SI61hksDLumoPi+0G9
+                1baQk0sG+Ibm5O5JuC/ihkO0jNs6ixbqdsAkF5ac3p1bgybNUIXKKZtn42nBKh7EXKprftdEAP2L
+                NcrhI76OmoxrxAus0OUIE1ZyOoLYeyI9/DewvedNwmN/BOw2PTmK72F1WPNcKmWAAuTnjk9qL/C2
+                cmV9DmjH16TB3Yuk4wp7FuVD5Uv5mKu5lbJxgTt+0NmwaUd83fvUBzTNnKKrAheopw+asrGR1Xbx
+                r24b7yOQaMSScgyqegszS855lSO5tD+b6w/wTsW2IUF0DyifVEE8/qJwgmFiBKr9FvG7A2POI3VN
+                UZivySATRLd/iL2gfxuU8Fs2FXks+Iec9B6mKDzDobeRoy7gMY/FjSdiVbfwwAokBAlBQn3bKD2E
+                t2me3MDCKsDVjPe0Ii4go3T2yScRrKjSyan+Ac2PmuOATD+76gdd56phbMNqS96+k43zVP8uuJGy
+                6ZFOyQeea7/8JhxXc/dZBQ7QuZp7w3kWP6FSv/kiQZmphdGkizTf6k/DWHu+uKA5VmF7DFcyeMEV
+                A4PcB3eT5g7+dmfIWiV2i01i0B0VRB05ctQnAdwPrv0nIgO5IK4+uKrVyDtEHOavYQNjrphy65lc
+                DH/+zP+2SdmDBxkXAlMcDSVZ/0qMexjgcqBDgDa7T4U4llWPxf0U5vfgYqRizz69WriIztVKRSU7
+                yHslW5fF9YSMgJNBn50mu5+cs+02wRfM9Zab3hXeT4XRWWJrE4hSWhRznqgrOYqDBSUYL937hcct
+                RXwkteLu1qNfTKLU6m2K8ilISC7wPBXyvhaYzRzpc0O2bljL9Nn9jzfqw5ZxGr7/wU+GnaDQ/2SE
+                3DJh4DwaVphjRmwioc6sJhKEjiCl6lJ6hNPBzWTvVMI0J82uhn/+pw2/Vdv4gJYEHYGqBV8KqC1V
+                6C8M+FPaRp4yxHUUv6ZDPblUzG8nDz/thF59WybJQdm6skxsIxELMEQ4ZPB13lLyS+cE0vMOC3bH
+                eor3vvQLUm+Hxvg8WDUhWDmRT+JOGuttn9TI7+8O6gi7aCSeL+yJULG4qD82DVyiqeU/XC4GxhFV
+                izb5sBkGqgTY5esR6VQ/RTMcCnsF8pKGuH8ROEucVGFE6qgWyCJdZHtR1udhHDksXpx5B67737Lp
+                wJgFd7Z3EM/y21J5ezbGyiBykMW5A5my2YILzUFLpkjEJgzdKTbYORIeyKkwnmqs01DOIaPw2c/1
+                sWxopmbrdeMpogifGR1B7VU2sl2CKWW008P/zXk33mKxYqfG9su8D7cWknZUBPJUFTNtypbYiFxv
+                3r56LcJobfsyFSK3FZW6x8SohS4VtQznwXxblPtEc8PeqVXPcoUGFtQev1Cnnheu5O8Mu89VpohV
+                QMfczucldoMhLWmknA2v64v9XCHmfApGxf2iY3Z3GGruPUH1uPcv9pIl+AL0AT8P0cdw885hkkie
+                lm0S85z6WxJvHoHAQp74CQP6HoTYF11I0ilQuxhk9Hkmhb9X5W2SQdEm6dTTYZt68rmi59E0Fv+k
+                vaaui81UbjsOiQ0pUgnDteyno9kDHpkDXzD/BgXojoZm+6tYZwqSjZAx/xbwj7wAVphobftTDH96
+                2MFrEYQKeHSNNxbWxdEopV+sWXJukKmv/t7aVlDSNKtveynL5W04WYEEWeFdimCVhB0FVwZ09wML
+                ra7zYKhGSOdREwE9NRYH/tpvPoZH3QsRiTw1uNszsmT5CTOAOVEmvPMNT9KP+Ja0YXL/4u3pLuqV
+                hDTHpkkzbBSeh9X1NrMw2E+sZU/s35HSbDayV3O7NMyOxDndHORt51YJmFQtUAshgN3+r3x0qwzS
+                G+tZpZvre7Fu09c0weBp+eJMQ8e3T4USaJ4Bk1RxecCozWssUGIe5siI1+s5qHhHBFDVpMqImt7E
+                JTBU1sFN8oWTPHw2CzkElmPUqX2Ssvw+8ZkSKpGYfqEe8+hYu8IDbH6E2rtFccH2oY0/xyGUb/XU
+                UhOoEssNduEwNod1HLwV0aGrEvSPlJQc2wTmj8uPdOaJVxNQEJlvAVDbbwwOuZr2Dv30dtqXV7PF
+                AaTLviF1zLQVK73ZwfVZRAtpO3Y0/FQoQXjyXAnvycaLCek5vSIf3SqcI+CyNzdnD97+U1E+J80c
+                7rICam4ZgXBp7Hu1M4EeSs8fBugdxR4mfRm3K88nF1FVKFRvXDCDj4sfhCcDzrgPfwY88II3pY+Y
+                YmF/9sHeJPKP0S1hA6Sg+9F8Jp4/bjpsotZf/E9M+zDuizVJioO42iyfZFiQ4BO4LnZsqk8NVu+o
+                6Cxm9EFVaRXcLf0D4JyzpAl5NdL8Wl0koJrb3/39w2/wT44xIbRE3wg0Asf+G866G/Ujmw471x6C
+                fgskId2sU5vuuGA0jjx+LxKqouIKgs/TvgucrWdOS9Q7d2xOkFv3czCrXieAUqqWq+6dn92qRz1v
+                fV3anKP4ilajGgR1/OxQ+BCu7xb1vdH3vmFebLGlc3fq4FUxeaE6aajQhOAtLMRIbGwPdE3nz1wy
+                4yznINDIuk0azxuIjDm0rxhPazdpIQZQfwTH2Y8XsJrejEv/N6PatwJ5rMxmTGJ1xDWgnQ7vydhD
+                g8KXzlzx6icMhghS3ppEv1zkByrz7MXaQgv4HMBhZOQ32/fBw77GXTeRBcKD7XUEPoKz2j1BukF3
+                84VxhW9UlF2QfQj2q2+hxNIrJnm7EW7UAckeIh0Ii537mz9JyOA3BJfOV9ABMuSW8U+WXRRLhVW8
+                w0A1V/6t12TpBsYnGfm+Cq3vItIDYTcP+QfIplqSp7MT4W9u7alz78A5zUV1Y8n/M9zJ3CMJ/rOi
+                7JvRZe1L9X4vSksuNpjBfu/aPhyg+Ua5i8yvVcUbvJ3iiH01VRDz9dEuSxO9ligj+eIO1JYvVNkh
+                n1WtKZDZM8v4Zmy3O7YxJ/3AKeCvVBUBMrIZ9ya/3NoUJJOTlIbKCc7zEPzvUm2Jsmqqq2GMW57f
+                CB69OFcEAxYNrls3mvr9pN5wmWolhvR1rDWej7qBNg9vqJm9PoKrT7NJRb/NcMI+Dcw2LbJm6fIN
+                QRAMUYsbFOU3WF40FBAZPFwIsdTiRVmoTyDxjtWVBizZbxK8txtg6kSBhT5cz9utiBMqxK9ifhtx
+                1hT3rPe+o1ZOxsThXi3qKZ7WUH7hbnQLbltbYfYHB15xaxP9dKQPB7gBJzQGIIZPVqzXBzi4anvQ
+                3ImxyMF7H7TY+p3Ldqc1Lfe+2OswTT9NRpZk3TkOHjk9n25LNQFtK4J1o482ZpvOJy9Ed0fvMpNZ
+                wwV8UVOHeBLNfVTEzoNfccO5iLRCKSq5BJmPsJOG6fpvGf2khtdtuIC7uEK306PNDVGZqdhvE7Qt
+                bcQk7k80PkDvz1LfjLw456U7Hru3TLwXUJPm5pE7X++EOw4UOqqSDg4E9xlspxssjJgN4qq2wsL6
+                9KTj4DI/u/NxqCHX/FJZ/YpGxLVvHPQashxMNAKfodNOx9d7lLIjV3aCvPTBOIqAz1UQ8dA4hUTY
+                SKlTLvpsa4pylbEbRI6EN0Dw08WO1KV2nDPJFkWUvZeG2Z5bzV4/yVp8wer+8w9MQfk0c9uyUAyC
+                EuxrYo+SgppbiqP1DRF3DH4x9h+fjGSZ3Xr1GV3g8YJ8IChh6NUBo/ned1m/pd64wD4ngCk59wkk
+                u2unZAmH87QUWLkQ0ZAujHd4z0B6ZXDloMuMKTfgZuJAMrsAlI+090UHhvbk8UeL2ab0cx/ruzcX
+                9jIUHRaF1JF8TpVoiZk+9Mzswh1RKSEwTKLmWARJmPqn4dpCjNzlCqGzgmi9FeuDkFT2yOVRemGO
+                7LdfHox8M+lv79HJWSJqe1Ex11lPzDiFq8ypsPVsqbTPgRVzCajsCEqy8EybLqHxt424T9iCkT6I
+                bWDW+FJ4dLsQxP26snScFOWmhbaNspR8InWaihvFzVufjm1fnZdPRhan/p0p4ADbCjGRTX7QdSCj
+                syeSaQrKYCOAhJNF4sW3fO8ZPsQ4G5EaRhrRdTxmFgz64rN3LAsAHeSbA1YWbjsIWebNMVYJp6vZ
+                6hY8scmzprgsitwLCLK2Fxo0NYRbI7fBKiNBJDA+2FkEB29B2tttnK5c7V50C/SqfxPveNbqzudu
+                St9Par7xpgqkN8uWAfjFwu47jRZlLyk7HDBoe1EhoILoJIIXcfQnY2TDtjNv/xcyYNHRttmPUH+w
+                ze9nOZ4g+MUGyf3IF9sE4qEKRvVUC2HBdbjAlRAKPx03n1dWQpbjzE5bBFDFl8Za5BESUZEUa4Pp
+                C+4S3P0VBqTJ+Yv6jZ7HZCLIyivbHDkgprS+/cSIClznhLca6bOO6//FUnG3ub+XgeKzOMdkBdpE
+                SLaAli7+ieCii23tD9QGaSW2JV1a2iIbXoZ6uwD9Pt9eSHfnnA9RLn6eSO+7+3vs/7R/JEk9KcZu
+                1IC7pCKqo4qBLSIymrqX20h9tk9ISovQXWFN3akjOviT0ZNLUgl4GvIRKsirl3Apnc3ktYGADqcy
+                RiOuzH4rDYuiOUAJOgI/VoatyhB1hG2WU3rqZXonpjDlYJUnVjcaiFek8D8smI/h+8L1mQgzSFVK
+                X5IPeHXfgE4tmqmiayD/cdxStJ68SKyDjHVZAfa4LHU9VAET26EgAuO9fVUYoHpziknstqcg4c6y
+                OY9Gh+Oo6L+6N0zb+RBTFUM8TMXTFjn1HZDYpNbImj1PQL92b9hx0TX6DFpkbUivl9nZ2TRnIjIK
+                nflp8jA03Knsb5XH6Uchn6QCEPxk+jAPIDEhrLB5dfWzDf16TDxjMZG9P+7cqG+HAXXU2kJovr6q
+                GDRbXEfjFlnsw5Shkbshjh7iCj+7QgV9Nmdmn1Z8vvNaz6i6wtz36C7Z3adyygDh6nJTGdRwlwDr
+                4r7LThrgMx/G6wfRveeOcRFD/n6boLzGwXK+wCqD7PjRyuV0QJ5/toenz9M5L3phQlpDDzM7JFvr
+                QEsFwiDguf7WoamAD7UYCc9ZshSUUmM+2dj7M/CpV+dCcRdVwH68406sxHhjnUYKwB86/FK/Ay3c
+                R1HebyLW2374Mm8E6qXb5v0qZQT2Gp7eVoFHWIlP7t8/y5xxQyirqpRcOq3elhg0LTTzQ91S+j2A
+                xqCGb5pElNQJmLu9hh3IihpO/yWNP9AEhZJoACVtabBjJKLRLO5XkQZ3wo6AWbdsFXn3ir6m+ex7
+                36vdAgUwfBpJUhHYCDOIV0Sj+Z1Oi/geebB/5Hvu6iMIlhI/gO1yT3Tada84Xg3KFuWMOp9QS/yu
+                up9HdLvSQKTXyBlrFXCJJ4LBZKcAlt5iOSVM+n7MvnS0hC4DE+nRNO7cpFe+rVKTlPvvlbxoOLN1
+                vQMpjdUnqVOvlCBO9QtVWCjve1IhcUrHCKWj6+JMlm6QspmD+SNVE+TtF9DvID2kkzmKUvXG/llg
+                bNqz/moupl60xjl8I1WBzzevVn0jEWh77D0TOhsLu9iNzOJgNoCr1aKRUAZcslFVm/BcIHo3oLSo
+                npa2bIQU2wyd1q8s1x2tyGqcGYLiOzK0vCzJRI4u9HS6j7xAmVRxEMbIQkLjJ0snjoLn57nJm+9F
+                YI2ZxaIebdL53LAzHl7u7VuwpW5vXU42QZkrKeTKCPqmDbbTjzK2KJgmPk/Bb2IUSbasOCo1u+Uu
+                6DxAL5QxcUg11XgF202lp4xtaGE6Ztp54kOJl0q2WnF0147fJuLhKZ6xH4C3AAAAnOC4P8r+AxMA
+                AYsrgOADAIsbpW6xxGf7AgAAAAAEWVo=
+                EOF
 
-                        ;;
-                    debian|ubuntu)
-                        wait_for_apt && apt update && \
-                        wait_for_apt && apt install -y xfce4 firefox
-                        if "$VERSION_ID" = "16.04" ]; then
-                            wget -O tigervnc.tar.gz https://bintray.com/tigervnc/stable/download_file?file_path=tigervnc-1.9.0.x86_64.tar.gz && \
-                            tar --strip-components=1 -zxvf tigervnc.tar.gz -C / || exit $?
-                            rm -rf tigervnc.tar.gz
-                        else
-                            wait_for_apt && apt install -y tigervnc-standalone-server || exit $?
-                        fi
-                        systemctl enable vncserver@:0.service && \
-                        systemctl enable vncconfig@:0.service && \
-                        systemctl restart vncserver@:0.service && \
-                        systemctl restart vncconfig@:0.service
-                        ;;
-                    *)
-                        echo "unsupported OS type '$LINUX_KIND'"
-                        exit 1;;
-                esac
+                base64 -d /var/tmp/remotedesktop_conf.tar.xz.encoded | tar -Jxvf -C ~{{.Username}} - && \
+                rm -f /var/tmp/remotedesktop_conf.tar.xz.encoded && \
+                chown -R {{.Username}}:{{.Username}} ~{{.Username}} || exit $?
+
+                systemctl daemon-reload && \
+                systemctl enable vncserver@:0.service && \
+                systemctl enable vncconfig@:0.service && \
+                systemctl restart vncserver@:0.service && \
+                systemctl restart vncconfig@:0.service || exit $?
 
                 ###########################################################
                 # Prepares remotedesktop docker image, based on guacamole #
@@ -242,9 +351,10 @@ component:
                 # ----------------
                 # Needed packages
                 # ----------------
-                RUN apt-get update -y \
-                && apt-get upgrade -y \
-                && apt-get install -y \
+                # Note: at the time writing, dash update fails so hold it for now
+                RUN apt-mark hold dash
+                RUN apt update -y \
+                 && apt install -y \
                         build-essential \
                         gcc-6 \
                         libcairo2-dev \
@@ -281,8 +391,8 @@ component:
                 # Needed packages
                 # -----------------
                 RUN apt update -y \
-                && apt upgrade -y \
-                && apt install -y \
+                 && apt upgrade -y \
+                 && apt install -y \
                         libcairo2 \
                         libjpeg62-turbo \
                         libossp-uuid16 \
@@ -337,16 +447,21 @@ component:
 
                 # Guacd need sshd to authorize password authentication...
                 cat >>/etc/ssh/sshd_config <<-'EOF'
-                # Allow Password Authentication from cladm user for guacd to work
-                Match User cladm Address 172.17.0.0/16
+                # Allow Password Authentication from {{.Username}} user for guacd to work
+                Match User {{.Username}} Address 172.17.0.0/16
                     PasswordAuthentication yes
                 EOF
                 systemctl reload sshd
 
+                # Allow only gateway to connect to port 9080
+                iptables -A INPUT -p tcp -s {{.GatewayIP}} --dport 9080 -j ACCEPT
+                iptables -A INPUT -p tcp ! -s {{.GatewayIP}} --dport 9080 -j REJECT
+                save_iptables_rules
+
                 ###########################################################
                 # Starts remotedesktop container                          #
                 ###########################################################
-                docker run --rm -d --hostname remotedesktop --name remotedesktop -p "8080:8080" -p "8009:8009" remotedesktop:latest
+                docker run --rm -d --hostname remotedesktop --name remotedesktop -p "9080:8080" -p "9009:8009" remotedesktop:latest
 
             remove: |
                 docker rm -f remotedesktop
@@ -357,7 +472,7 @@ component:
 
     service:
         start: |
-            docker run --rm -d --hostname remotedesktop --name remotedesktop  -p "8080:8080" -p "8009:8009" remotedesktop:latest
+            docker run --rm -d --hostname remotedesktop --name remotedesktop  -p "9080:8080" -p "9009:8009" remotedesktop:latest
 
         pause: |
             docker stop remotedesktop
@@ -378,7 +493,7 @@ component:
               content: |
                 {
                     "name": "remotedesktop_{{.Hostname}}",
-                    "url": "http://{{.HostIP}}:8080/guacamole/"
+                    "url": "http://{{.HostIP}}:9080/guacamole/"
                 }
 
             - name: remotedesktop
