feat(97666 embedfeature dockerhub) docker login (#379)
Co-authored-by: pdavid-cs <pierre.david@csgroup.eu>

diff --git a/lib/server/resources/operations/embeddedfeatures/docker.yml b/lib/server/resources/operations/embeddedfeatures/docker.yml
--- a/lib/server/resources/operations/embeddedfeatures/docker.yml
+++ b/lib/server/resources/operations/embeddedfeatures/docker.yml
@@ -33,19 +33,16 @@ feature:
               fi
               echo $VERSION
               sfExit 0
-
         - name: DockerHubUsername
           value: ''
           description: |-
               Username to use to authenticate DockerHub (default: empty, disabling authentication)
               Note: not handled yet
-
         - name: DockerHubPassword
           value: ''
           description: |-
               Password to use to authenticate DockerHub (default: empty, useless if DockerHubUsername is empty)
               Note: not handle yet...
-
     install:
         bash:
             check:
@@ -101,9 +98,8 @@ feature:
                                     ;;
                             esac
                             sfExit
-
             add:
-                pace: cleanup,docker-ce,docker-compose,config,firewall,enable,verify
+                pace: cleanup,docker-ce,docker-compose,config,firewall,enable,verify,docker-login
                 steps:
                     cleanup:
                         targets:
@@ -134,7 +130,6 @@ feature:
                                     ;;
                             esac
                             sfExit
-
                     docker-ce:
                         targets:
                             hosts: yes
@@ -202,7 +197,6 @@ feature:
                                     ;;
                             esac
                             sfExit
-
                     docker-compose:
                         targets:
                             hosts: yes
@@ -221,7 +215,6 @@ feature:
                             sfDownload "$URL" docker-compose 3m 5 || sfFail 207 "error downloading last docker-compose ${VERSION}"
                             chmod +x docker-compose && mv docker-compose /usr/bin
                             sfExit
-
                     config:
                         targets:
                             hosts: yes
@@ -277,7 +270,6 @@ feature:
                             EOF
                             fi
                             sfExit
-
                     firewall:
                         targets:
                             gateways: all
@@ -288,7 +280,6 @@ feature:
                             # First once dockerd, allowing it to create needed firewalld zone docker...
                             sfFirewallReload || sfFail 208 "failed to reload firewalld, ensuring it works correctly"
                             sfService restart docker || sfFail 209 "failed to restart dockerd for the first time"
-
                             # ... and if no such zone is created, create needed firewalld rules
                             # FIXME: it should be better to create a configuration identical to the one created by docker 20.10+...
                             sfFirewall --info-zone=docker 2>&1 >/dev/null || {
@@ -297,7 +288,6 @@ feature:
                                 sfFirewallReload || sfFail 210 "Firewall problem"
                             }
                             sfExit
-
                     enable:
                         targets:
                             gateways: all
@@ -311,7 +301,6 @@ feature:
                             sfRetry "sfService status docker &>/dev/null" && op=$? || true
                             [ $op -ne 0 ] && sfFail 213
                             sfExit
-
                     verify:
                         targets:
                             gateways: all
@@ -323,17 +312,43 @@ feature:
                             sleep {{ or .reserved_DefaultDelay 10 }}
                             rm -f /tmp/docker-fail.txt || true
                             op=-1
-                            sfRetryEx 5m 5 "docker pull hello-world 2>>/tmp/fail.txt 7>>/tmp/fail.txt" && op=$? || op=$?
+                            sfRetryEx 5m 5 "docker pull hello-world 2>>/tmp/docker-fail.txt 7>>/tmp/docker-fail.txt" && op=$? || op=$?
                             if [[ $op -ne 0 ]]; then
                                 sfFail 214 "$(cat /tmp/docker-fail.txt)\nexit code $op"
                             fi
                             rm -f /tmp/docker-fail.txt || true
                             docker run hello-world | grep "working correctly" || sfFail 215 "failure running hello-world docker image"
                             sfExit
-
+                    docker-login:
+                        targets:
+                            gateways: all
+                            hosts: yes
+                            masters: all
+                            nodes: all
+                        run: |
+                            rm -f /tmp/docker-fail.txt || true
+                            if [[ "{{.DockerHubUsername}}" != "" ]]; then
+                                docker login --username="{{.DockerHubUsername}}" --password-stdin <<< "{{.DockerHubPassword}}" > /tmp/docker-fail.txt
+                                if [[ "$(cat /tmp/docker-fail.txt)" != "Login Succeeded" ]]; then
+                                    sfFail 216 "$(/tmp/cat docker-fail.txt)"
+                                fi
+                            fi
+                            rm -f /tmp/docker-fail.txt || true
+                            sfExit
             remove:
-                pace: cleanup
+                pace: docker-logout,cleanup
                 steps:
+                    docker-logout:
+                        targets:
+                            gateways: all
+                            hosts: yes
+                            masters: all
+                            nodes: all
+                        run: |
+                            if [[ "{{.DockerHubUsername}}" != "" ]]; then
+                                docker logout
+                            fi
+                            sfExit
                     cleanup:
                         targets:
                             gateways: all
@@ -343,16 +358,11 @@ feature:
                         run: |
                             sfService disable docker
                             sfService stop docker
-
                             sfFirewallAdd --zone=trusted --remove-interface=docker0 --remove-interface=docker_gwbridge
                             sfFirewallReload || sfFail 192 "Firewall problem"
-
                             case $LINUX_KIND in
-                                ubuntu)
-                                    sfApt remove -qqy docker-ce*
-                                    ;;
                                 debian|ubuntu)
-                                    dpkg --purge --force-remove-reinstreq docker-ce docker-ce-cli docker-ce-rootless-extras
+                                    dpkg --purge --force-remove-reinstreq docker-ce*
                                     ;;
                                 centos|redhat|rhel)
                                     yum remove -y docker-ce*
@@ -367,5 +377,4 @@ feature:
                             esac
                             rm -f /usr/bin/docker-compose || true
                             sfExit
-
 ...
