Added missing certificateauthority embedded feature
+ code cleanup

diff --git a/lib/server/resources/operations/features/kubernetes.yml b/lib/server/resources/operations/features/kubernetes.yml
--- a/lib/server/resources/operations/features/kubernetes.yml
+++ b/lib/server/resources/operations/features/kubernetes.yml
@@ -113,16 +113,16 @@ feature:
                                 modprobe $i 2>/dev/null && op=0 || true
                             done
                             if [ $op -eq -1 ]; then
-                                sfFail 201 "Error enabling kernel module nf_conntrack and nf_conntrack_ipv4"
+                                sfFail 192 "Error enabling kernel module nf_conntrack and nf_conntrack_ipv4"
                             fi
 
                             case $LINUX_KIND in
                                 debian|ubuntu)
                                     sfWaitForApt
-                                    sfStandardRetry sfApt install -y ebtables socat || sfFail 192
+                                    sfStandardRetry sfApt install -y ebtables socat || sfFail 193
                                     ;;
                                 redhat|rhel|fedora|centos)
-                                    sfStandardRetry yum install -y ebtables socat || sfFail 193
+                                    sfStandardRetry yum install -y ebtables socat || sfFail 194
 
                                     cat >/etc/sysctl.d/kubernetes.conf <<-'EOF'
                             net.bridge.bridge-nf-call-ip6tables = 1
@@ -144,7 +144,7 @@ feature:
                                     ;;
                                 *)
                                     echo "Unmanaged Linux distribution '$LINUX_KIND'"
-                                    sfFail 194
+                                    sfFail 195
                                     ;;
                             esac
 
@@ -178,15 +178,15 @@ feature:
                                 case $(sfGetFact "linux_kind") in
                                     debian|ubuntu)
                                         sfApt update
-                                        sfStandardRetry sfApt install -y auditd quota quotatool || sfFail 195
+                                        sfStandardRetry sfApt install -y auditd quota quotatool || sfFail 196
                                         ;;
 
                                     centos|fedora|redhat|rhel)
-                                        sfStandardRetry yum -y install audit audit-libs quota || sfFail 195
+                                        sfStandardRetry yum -y install audit audit-libs quota || sfFail 197
                                         ;;
 
                                     *) echo "unsupported linux distribution '$(sfGetFact "linux_kind")'"
-                                    sfFail 196
+                                    sfFail 198
                                     ;;
                                 esac
 
@@ -214,7 +214,7 @@ feature:
                             # Disable docker swarm
                             cat /etc/docker/daemon.json | jq '. + { "swarm-default-advertise-addr": "" }' >/etc/docker/daemon.json.new && \
                             mv /etc/docker/daemon.json.new /etc/docker/daemon.json && \
-                            sfService restart docker || sfFail 198 "failed to disable docker swarm"
+                            sfService restart docker || sfFail 199 "failed to disable docker swarm"
                             {{ end }}
                             sfExit
 
@@ -235,7 +235,7 @@ feature:
                             {{ if .KubeVersion }}
                                     sfApt update && sfApt install -y kubelet={{.KubeVersion}}-00 kubeadm={{.KubeVersion}}-00 kubectl={{.KubeVersion}}-00 || sfFail 199
                             {{ else }}
-                                    sfApt update && sfApt install -y kubelet kubeadm kubectl || sfFail 199
+                                    sfApt update && sfApt install -y kubelet kubeadm kubectl || sfFail 200
                             {{ end }}
                                     apt-mark hold kubelet kubeadm kubectl
                                     ;;
@@ -255,12 +255,12 @@ feature:
                             {{ if .KubeVersion }}
                                     yum -y install kubelet-{{.KubeVersion}} kubeadm-{{.KubeVersion}} kubectl-{{.KubeVersion}} --disableexcludes=kubernetes || sfFail 199
                             {{ else }}
-                                    yum -y install kubelet kubeadm kubectl --disableexcludes=kubernetes || sfFail 199
+                                    yum -y install kubelet kubeadm kubectl --disableexcludes=kubernetes || sfFail 201
                             {{ end }}
                                     ;;
 
                                 *) echo "unsupported linux distribution ''"
-                                   sfFail 200
+                                   sfFail 202
                             esac
                             sfService enable kubelet && sfService start kubelet
 
@@ -275,13 +275,13 @@ feature:
                             {{ if .ClusterControlplaneUsesVIP }}
                             case $(sfGetFact "linux_kind") in
                                 ubuntu|debian)
-                                    sfApt update && sfApt -y install keepalived haproxy || sfFail 202
+                                    sfApt update && sfApt -y install keepalived haproxy || sfFail 203
                                     ;;
                                 redhat|rhel|centos|fedora)
-                                    yum install -q -y keepalived haproxy || sfFail 202
+                                    yum install -q -y keepalived haproxy || sfFail 204
                                     ;;
                                 *)
-                                    sfFail 203 "Unsupported Linux distribution '$(sfGetFact "linux_kind")'!"
+                                    sfFail 205 "Unsupported Linux distribution '$(sfGetFact "linux_kind")'!"
                                     ;;
                             esac
 
@@ -344,7 +344,7 @@ feature:
                             fi
 
                             sfService enable keepalived
-                            sfService restart keepalived || sfFail 204
+                            sfService restart keepalived || sfFail 206
 
                             ## Configure haproxy as TCP load-balancer for kubernetes Control Plane
                             cat >/etc/haproxy/haproxy.cfg <<-EOF
@@ -402,7 +402,7 @@ feature:
                             EOF
                             mkdir -p /var/local/haproxy
                             sfService enable haproxy
-                            sfService restart haproxy || sfFail 205
+                            sfService restart haproxy || sfFail 207
                             {{ end }}
                             sfExit
 
@@ -519,10 +519,10 @@ feature:
                             metricsBindAddress: 0.0.0.0:10249
                             EOF
 
-                            sfRetry {{.TemplatePullImagesTimeout}} $(sfDefaultDelay) kubeadm config images pull || sfFail 202
-                            sudo kubeadm init --config=/etc/kubernetes/kubeadm/kubeadm-config.yaml || sfFail 203
-                            cp_join_cmd=$(kubeadm token create --ttl 10m --print-join-command) || sfFail 204
-                            cert_key=$(kubeadm init phase upload-certs --upload-certs | tail -n 1) || sfFail 205
+                            sfRetry $(sfDockerImagePullTimeout) $(sfDefaultDelay) kubeadm config images pull || sfFail 208
+                            sudo kubeadm init --config=/etc/kubernetes/kubeadm/kubeadm-config.yaml || sfFail 209
+                            cp_join_cmd=$(kubeadm token create --ttl 10m --print-join-command) || sfFail 210
+                            cert_key=$(kubeadm init phase upload-certs --upload-certs | tail -n 1) || sfFail 211
 
                             cat >${SF_TMPDIR}/init_cluster_admin_kube.sh <<-'EOF'
                             mkdir -p ~{{.ClusterAdminUsername}}/.kube
@@ -538,7 +538,7 @@ feature:
                             EOF
 
                             # execute init_cluster_admin_kube.sh on the current master
-                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || sfFail 206
+                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || sfFail 212
                             # Starting from here, any kubectl command must be changed to sfKubectl
 
                             # Push control-plane join command to all the other masters
@@ -546,11 +546,11 @@ feature:
                             kubeadm reset --force
                             $cp_join_cmd --control-plane --certificate-key $cert_key --apiserver-bind-port $LOCAL_PORT
                             EOF
-                            sfDropzonePush ${SF_TMPDIR}/cp_join_cmd.sh || fail 207
-                            sfDropzonePush ${SF_TMPDIR}/init_cluster_admin_kube.sh || fail 208
+                            sfDropzonePush ${SF_TMPDIR}/cp_join_cmd.sh || fail 213
+                            sfDropzonePush ${SF_TMPDIR}/init_cluster_admin_kube.sh || fail 214
                             for ip in {{range .ClusterMasterIPs}}{{.}} {{end}}; do
                                 [ "$ip" = "{{.HostIP}}" ] && continue
-                                sfDropzoneSync $ip || sfFail 209
+                                sfDropzoneSync $ip || sfFail 215
                             done
                             rm ${SF_TMPDIR}/cp_join_cmd.sh ${SF_TMPDIR}/init_cluster_admin_kube.sh
                             sfDropzoneClean
@@ -681,15 +681,15 @@ feature:
                               resourceNames: ['privileged']
                             EOF
 
-                            sfKubectl apply -f /etc/kubernetes/kubeadm/psp-default.yaml || sfFail 204
-                            sfKubectl apply -f /etc/kubernetes/kubeadm/psp-privileged.yaml || sfFail 205
+                            sfKubectl apply -f /etc/kubernetes/kubeadm/psp-default.yaml || sfFail 216
+                            sfKubectl apply -f /etc/kubernetes/kubeadm/psp-privileged.yaml || sfFail 217
                             {{ end }}
 
                             # waits availability of key pods
                             set -u -o pipefail
-                            sfStandardRetry sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || sfFail 212
-                            sfStandardRetry sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system || sfFail 213
-                            sfStandardRetry sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || sfFail 214
+                            sfStandardRetry sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || sfFail 218
+                            sfStandardRetry sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system || sfFail 219
+                            sfStandardRetry sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || sfFail 220
 
                             echo "cp1 init done"
                             sfExit
@@ -703,11 +703,11 @@ feature:
                             case {{ .CNI }} in
                                 flannel)
                                     # Apply Flannel yaml
-                                    sfKubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.12.0/Documentation/kube-flannel.yml || sfFail 215
+                                    sfKubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.12.0/Documentation/kube-flannel.yml || sfFail 221
                                     ;;
                                 calico)
                                     # Download Calico yaml
-                                    wget https://docs.projectcalico.org/archive/v3.15/manifests/calico.yaml -P ${SF_TMPDIR} || sfFail 220
+                                    wget https://docs.projectcalico.org/archive/v3.15/manifests/calico.yaml -P ${SF_TMPDIR} || sfFail 222
 
                                     # Configure Pods subnet
                                     sed -i 's/# - name: CALICO_IPV4POOL_CIDR/- name: CALICO_IPV4POOL_CIDR/g' ${SF_TMPDIR}/calico.yaml
@@ -721,7 +721,7 @@ feature:
                                     {{ end }}
 
                                     # Apply Calico yaml
-                                    sfKubectl apply -f ${SF_TMPDIR}/calico.yaml || sfFail 224
+                                    sfKubectl apply -f ${SF_TMPDIR}/calico.yaml || sfFail 223
                                     rm ${SF_TMPDIR}/calico.yaml
                                     ;;
                             esac
@@ -737,20 +737,20 @@ feature:
                             # Don't try to init a kubernetes cluster already running
                             [ -f /etc/kubernetes/.joined ] && sfExit
 
-                            sfDropzonePop ${SF_TMPDIR} || sfFail 223
+                            sfDropzonePop ${SF_TMPDIR} || sfFail 224
                             sfDropzoneClean
 
-                            [ -f ${SF_TMPDIR}/cp_join_cmd.sh ] || sfFail 227
+                            [ -f ${SF_TMPDIR}/cp_join_cmd.sh ] || sfFail 225
                             # sometimes, etcd cluster appears to be unhealthy when calling this... So retries!
-                            sfRetry $(sfLongTimeout) $(sfDefaultDelay) bash ${SF_TMPDIR}/cp_join_cmd.sh || sfFail 228
-                            [ -f ${SF_TMPDIR}/init_cluster_admin_kube.sh ] || sfFail 229
-                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || sfFail 230
+                            sfRetry $(sfLongTimeout) $(sfDefaultDelay) bash ${SF_TMPDIR}/cp_join_cmd.sh || sfFail 226
+                            [ -f ${SF_TMPDIR}/init_cluster_admin_kube.sh ] || sfFail 227
+                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || sfFail 228
 
                             # waits availability of key pods
                             set -u -o pipefail
-                            sfStandardRetry sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || sfFail 228
-                            sfStandardRetry sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system || sfFail 229
-                            sfStandardRetry sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || sfFail 230
+                            sfStandardRetry sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || sfFail 229
+                            sfStandardRetry sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system || sfFail 230
+                            sfStandardRetry sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || sfFail 231
 
                             touch /etc/kubernetes/.joined
                             echo "cpx init done"
@@ -771,10 +771,10 @@ feature:
                                 MASTERIP=$m
                                 break
                             done
-                            [ -z "$MASTERIP" ] && echo "failed to find available master to register with. Aborted." && sfFail 233
-                            eval $NODE_JOIN_CMD || sfFail 234
+                            [ -z "$MASTERIP" ] && echo "failed to find available master to register with. Aborted." && sfFail 232
+                            eval $NODE_JOIN_CMD || sfFail 233
 
-                            sfRemoteExec $MASTERIP sudo -u {{ .ClusterAdminUsername }} -i kubectl taint nodes {{ .Hostname }} key=value:NoSchedule || sfFail 235
+                            sfRemoteExec $MASTERIP sudo -u {{ .ClusterAdminUsername }} -i kubectl taint nodes {{ .Hostname }} key=value:NoSchedule || sfFail 234
 
                             touch /etc/kubernetes/.joined
                             sfExit
@@ -794,8 +794,8 @@ feature:
                                 MASTERIP=$m
                                 break
                             done
-                            [ -z "$MASTERIP" ] && echo "failed to find available master to register with. Aborted." && sfFail 233
-                            eval $NODE_JOIN_CMD || sfFail 234
+                            [ -z "$MASTERIP" ] && echo "failed to find available master to register with. Aborted." && sfFail 235
+                            eval $NODE_JOIN_CMD || sfFail 236
 
                             touch /etc/kubernetes/.joined
                             sfExit
@@ -818,10 +818,10 @@ feature:
                             # adds Kubernetes Dashboard
                             if [ "{{.Dashboard}}" == "true" ]; then
                                 if curl --output /dev/null --silent --head --fail "https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml"; then
-                                    sfStandardRetry sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || sfFail 254 "Unable to install kubernetes dashboard version $(sfGithubLastRelease)"
+                                    sfStandardRetry sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || sfFail 237 "Unable to install kubernetes dashboard version $(sfGithubLastRelease)"
                                 else
                                     if curl --output /dev/null --silent --head --fail "https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastNotBetaRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml"; then
-                                        sfStandardRetry sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastNotBetaRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || sfFail 255 "Unable to install kubernetes dashboard version $(sfGithubLastNotBetaRelease)"
+                                        sfStandardRetry sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastNotBetaRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || sfFail 238 "Unable to install kubernetes dashboard version $(sfGithubLastNotBetaRelease)"
                                     fi
                                 fi
                             fi
@@ -855,13 +855,13 @@ feature:
                         run: |
                             case $LINUX_KIND in
                                 debian|ubuntu)
-                                    sfApt purge -y kubectl kubeadm kubelet || sfFail 223 "failure purging kubernetes"
+                                    sfApt purge -y kubectl kubeadm kubelet || sfFail 192 "failure purging kubernetes"
                                     ;;
                                 redhat|rhel|fedora|centos)
-                                    yum remove -y kubectl kubeadm kubelet || sfFail 224 "failure purging kubernetes"
+                                    yum remove -y kubectl kubeadm kubelet || sfFail 193 "failure purging kubernetes"
                                     ;;
                             esac
-                            sfFirewallReload || sfFail 225 "Firewall problem"
+                            sfFirewallReload || sfFail 194 "Firewall problem"
                             rm -f /etc/kubernetes/.joined
                             sfExit
 
