Using fail instead of exit in features

diff --git a/features/edgeproxy4network.yml b/features/edgeproxy4network.yml
--- a/features/edgeproxy4network.yml
+++ b/features/edgeproxy4network.yml
@@ -35,7 +35,7 @@ feature:
                             masters: no
                             nodes: no
                         run: |
-                            curl -Ssl -I -k https://localhost:8444/ 2>&1 | grep HTTP | grep 200 | grep OK &>/dev/null || exit 192
+                            curl -Ssl -I -k https://localhost:8444/ 2>&1 | grep HTTP | grep 200 | grep OK &>/dev/null || fail 192
 
             add:
 #                pace: config,secret,networks,start
@@ -163,7 +163,7 @@ feature:
                                         - "127.0.0.1:8444:8444"
                                     restart: always
                                     healthcheck:
-                                        test: ["CMD-SHELL", "curl -I -s -k -L https://127.0.0.1:8444 || exit 1"]
+                                        test: ["CMD-SHELL", "curl -I -s -k -L https://127.0.0.1:8444 || fail 1"]
                                         interval: 5s
                                         retries: 10
                             #         secrets:
@@ -230,7 +230,7 @@ feature:
                     #         nodes: no
                     #     run: |
                     #         docker secret rm safescale.edgeproxy.db_password &>/dev/null || true
-                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.edgeproxy.db_password - &>/dev/null || exit 192
+                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.edgeproxy.db_password - &>/dev/null || fail 192
                     #         exit 0
 
                     networks:
@@ -266,8 +266,8 @@ feature:
                             masters: no
                             nodes: no
                         run: |
-                            docker-compose -f ${SF_ETCDIR}/edgeproxy4network/docker-compose.yml -p edgeproxy4network up -d || exit 193
-                            sfRetry 5m 5 "sfDoesDockerRunContainer edgeproxy4network:latest edgeproxy4network_proxy_1" || exit 194
+                            docker-compose -f ${SF_ETCDIR}/edgeproxy4network/docker-compose.yml -p edgeproxy4network up -d || fail 193
+                            sfRetry 5m 5 "sfDoesDockerRunContainer edgeproxy4network:latest edgeproxy4network_proxy_1" || fail 194
                             exit 0
 
             remove:
@@ -281,19 +281,19 @@ feature:
                             nodes: no
                         run: |
                             if [ -f ${SF_ETCDIR}/edgeproxy4network/docker-compose.yml ]; then
-                                docker-compose -f ${SF_ETCDIR}/edgeproxy4network/docker-compose.yml -p edgeproxy4network rm --stop --force || exit 195
+                                docker-compose -f ${SF_ETCDIR}/edgeproxy4network/docker-compose.yml -p edgeproxy4network rm --stop --force || fail 195
                                 # docker secret rm safescale.edgeproxy.db_password &>/dev/null
                                 docker image rm -f edgeproxy4network:latest
                                 rm -rf ${SF_ETCDIR}/edgeproxy4network
 
                             else
                                 if [ -f ${SF_ETCDIR}/kong4gateway/docker-compose.yml ]; then
-                                    docker-compose -f ${SF_ETCDIR}/kong4gateway/docker-compose.yml -p kong4gateway rm --stop --force || exit 196
+                                    docker-compose -f ${SF_ETCDIR}/kong4gateway/docker-compose.yml -p kong4gateway rm --stop --force || fail 196
                                     docker image rm -f kong4gateway:latest
                                     rm -rf ${SF_ETCDIR}/kong4gateway
                                 fi
                                 if [ -f ${SF_ETCDIR}/kong/docker-compose.yml ]; then
-                                    docker-compose -f ${SF_ETCDIR}/kong/docker-compose.yml -p kong rm --stop --force || exit 197
+                                    docker-compose -f ${SF_ETCDIR}/kong/docker-compose.yml -p kong rm --stop --force || fail 197
                                     docker image rm -f kong:latest
                                     rm -rf ${SF_ETCDIR}/kong
                                 fi
diff --git a/features/keycloak4gateway.yml b/features/keycloak4gateway.yml
--- a/features/keycloak4gateway.yml
+++ b/features/keycloak4gateway.yml
@@ -205,7 +205,7 @@ feature:
                             CMD ["-b", "0.0.0.0"]
                             EOF
 
-                            docker build -t keycloak4gateway:latest ${SF_ETCDIR}/keycloak4gateway || exit 192
+                            docker build -t keycloak4gateway:latest ${SF_ETCDIR}/keycloak4gateway || fail 192
 
                     # secret:
                     #     targets:
@@ -215,8 +215,8 @@ feature:
                     #         nodes: no
                     #     run: |
                     #         docker secret rm keycloak4gateway-db keycloak4gateway-admin &>/dev/null || true
-                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create keycloak4gateway-db - || exit 193
-                    #         echo -n "{{ .KeycloakAdminPassword }}" | docker secret create keycloak4gateway-admin - || exit 193
+                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create keycloak4gateway-db - || fail 193
+                    #         echo -n "{{ .KeycloakAdminPassword }}" | docker secret create keycloak4gateway-admin - || fail 193
                     #         exit 0
 
                     compose:
@@ -285,8 +285,8 @@ feature:
                             masters: no
                             nodes: no
                         run: |
-                            docker-compose -f ${SF_ETCDIR}/keycloak4gateway/docker-compose.yml -p keycloak4gateway up -d || exit 194
-                            sfRetry 5m 5 "sfDoesDockerRunContainer keycloak4gateway:latest keycloak4gateway_server_1" || exit 195
+                            docker-compose -f ${SF_ETCDIR}/keycloak4gateway/docker-compose.yml -p keycloak4gateway up -d || fail 194
+                            sfRetry 5m 5 "sfDoesDockerRunContainer keycloak4gateway:latest keycloak4gateway_server_1" || fail 195
                             exit 0
 
             remove:
@@ -299,7 +299,7 @@ feature:
                             masters: no
                             nodes: no
                         run: |
-                            docker-compose -f ${SF_ETCDIR}/keycloak4gateway/docker-compose.yml -p keycloak4gateway rm --stop --force || exit 196
+                            docker-compose -f ${SF_ETCDIR}/keycloak4gateway/docker-compose.yml -p keycloak4gateway rm --stop --force || fail 196
                             exit 0
 
                     cleanup:
diff --git a/features/kong4safescale.yml b/features/kong4safescale.yml
--- a/features/kong4safescale.yml
+++ b/features/kong4safescale.yml
@@ -171,7 +171,7 @@ feature:
 
                             CMD ["kong", "docker-start"]
                             EOF
-                            docker build --network host -t kong4safescale:latest ${SF_ETCDIR}/kong4safescale/build || exit 192
+                            docker build --network host -t kong4safescale:latest ${SF_ETCDIR}/kong4safescale/build || fail 192
                             exit 0
 
                     stack:
@@ -233,7 +233,7 @@ feature:
                                             max_attempts: 3
                                             window: 120s
                                     # healthcheck:
-                                    #     test: ["CMD-SHELL", "curl -I -s -k -L https://127.0.0.1:8444 || exit 1"]
+                                    #     test: ["CMD-SHELL", "curl -I -s -k -L https://127.0.0.1:8444 || fail 1"]
                                     #     interval: 5s
                                     #     retries: 10
                                     secrets:
@@ -292,7 +292,7 @@ feature:
                             nodes: no
                         run: |
                             docker secret rm safescale.kong.db_password &>/dev/null || true
-                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.kong.db_password - &>/dev/null || exit 193
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.kong.db_password - &>/dev/null || fail 193
                             exit 0
 
                     start:
@@ -302,8 +302,8 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            docker stack deploy -c ${SF_ETCDIR}/kong4safescale/stack.yml kong4safescale || exit 194
-                            sfRetry 5m 5 "sfDoesDockerRunService kong4safescale:latest kong4safescale_proxy" || exit 195
+                            docker stack deploy -c ${SF_ETCDIR}/kong4safescale/stack.yml kong4safescale || fail 194
+                            sfRetry 5m 5 "sfDoesDockerRunService kong4safescale:latest kong4safescale_proxy" || fail 195
                             exit 0
 
             remove:
@@ -316,7 +316,7 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            docker stack rm kong4safescale  || exit 196
+                            docker stack rm kong4safescale  || fail 196
                             docker secret rm safescale.kong.db_password &>/dev/null
                             exit 0
 
diff --git a/features/kubernetes.yml b/features/kubernetes.yml
--- a/features/kubernetes.yml
+++ b/features/kubernetes.yml
@@ -117,7 +117,7 @@ feature:
                             output=$(sfDcos package install --yes kubernetes {{.options}} 2>&1) && op=$? || true
                             [ $op -ne 0 ] && {
                                 echo $output
-                                echo $output | grep "already installed" &>/dev/null || exit $op
+                                echo $output | grep "already installed" &>/dev/null || fail $op
                             }
                             exit 0
 
@@ -131,7 +131,7 @@ feature:
                         targets:
                             masters: all
                         run: |
-                            sfRetry 10m 20 sfDcos kubernetes plan show deploy --json | jq .status | grep COMPLETE &>/dev/null || exit 192
+                            sfRetry 10m 20 sfDcos kubernetes plan show deploy --json | jq .status | grep COMPLETE &>/dev/null || fail 192
                             sfDcos kubernetes kubeconfig --apiserver-url https://apiserver.kubernetes.l4lb.thisdcos.directory:6443 && \
                             sfDcos config set-cluster kubernetes --server https://apiserver.kubernetes.l4lb.thisdcos.directory:6443
 
@@ -177,7 +177,7 @@ feature:
                                     cat >/etc/apt/sources.list.d/kubernetes.list <<-EOF
                             deb https://apt.kubernetes.io/ kubernetes-xenial main
                             EOF
-                                    sfApt update && sfApt install -y kubelet kubeadm kubectl || exit 192
+                                    sfApt update && sfApt install -y kubelet kubeadm kubectl || fail 192
                                     apt-mark hold kubelet kubeadm kubectl
                                     ;;
 
@@ -193,7 +193,7 @@ feature:
                             exclude=kube*
                             EOF
 
-                                    yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes || exit 192
+                                    yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes || fail 192
                                     ;;
 
                                 *) echo "unsupported linux distribution ''"
@@ -212,10 +212,10 @@ feature:
                             case $LINUX_KIND in
                                 debian|ubuntu)
                                     sfWaitForApt
-                                    sfRetry 5m 5 sfApt install -y ebtables socat || exit 194
+                                    sfRetry 5m 5 sfApt install -y ebtables socat || fail 194
                                     ;;
                                 redhat|centos)
-                                    sfRetry 5m 5 yum install -y ebtables socat || exit 195
+                                    sfRetry 5m 5 yum install -y ebtables socat || fail 195
                                     cat >/etc/sysctl.d/kubernetes.conf <<-'EOF'
                             net.bridge.bridge-nf-call-ip6tables = 1
                             net.bridge.bridge-nf-call-iptables = 1
@@ -301,11 +301,11 @@ feature:
                             # EOF
                             # fi
 
-                            sfRetry 5m 5 kubeadm config images pull || exit 198
-                            kubeadm init --config=/etc/kubernetes/kubeadm/kubeadm-config.yaml || exit 199
-                            cp_join_cmd=$(kubeadm token create --ttl 10m --print-join-command) || exit 200
-                            #cert_key=$(kubeadm init phase upload-certs --experimental-upload-certs | tail -1) || exit 201
-                            cert_key=$(kubeadm init phase upload-certs --upload-certs | tail -1) || exit 201
+                            sfRetry 5m 5 kubeadm config images pull || fail 198
+                            kubeadm init --config=/etc/kubernetes/kubeadm/kubeadm-config.yaml || fail 199
+                            cp_join_cmd=$(kubeadm token create --ttl 10m --print-join-command) || fail 200
+                            #cert_key=$(kubeadm init phase upload-certs --experimental-upload-certs | tail -1) || fail 201
+                            cert_key=$(kubeadm init phase upload-certs --upload-certs | tail -1) || fail 201
 
                             cat >${SF_TMPDIR}/init_cluster_admin_kube.sh <<-'EOF'
                             mkdir -p ~{{.Username}}/.kube
@@ -315,17 +315,17 @@ feature:
                             EOF
 
                             # execute init_cluster_admin_kube.sh on the current master
-                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || exit 202
+                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || fail 202
                             # Starting from here, any kubectl command must be changed to sfKubectl
 
                             # Push control-plane join command to all the other masters
                             echo "$cp_join_cmd --experimental-control-plane --certificate-key $cert_key" >${SF_TMPDIR}/cp_join_cmd.sh
                             cat ${SF_TMPDIR}/cp_join_cmd.sh
-                            sfDropzonePush ${SF_TMPDIR}/cp_join_cmd.sh || exit 203
-                            sfDropzonePush ${SF_TMPDIR}/init_cluster_admin_kube.sh || exit 204
+                            sfDropzonePush ${SF_TMPDIR}/cp_join_cmd.sh || fail 203
+                            sfDropzonePush ${SF_TMPDIR}/init_cluster_admin_kube.sh || fail 204
                             for ip in {{range .MasterIPs}}{{.}} {{end}}; do
                                 [ "$ip" = "{{.HostIP}}" ] && continue
-                                sfDropzoneSync $ip || exit 205
+                                sfDropzoneSync $ip || fail 205
                             done
                             rm ${SF_TMPDIR}/cp_join_cmd.sh ${SF_TMPDIR}/init_cluster_admin_kube.sh
                             sfDropzoneClean
@@ -333,9 +333,9 @@ feature:
                             # waits availability of key pods
                             
                             set -u -o pipefail
-                            sfRetry 5m 10 sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || exit 206
-                            sfRetry 5m 10 sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system || exit 207
-                            sfRetry 5m 10 sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || exit 208
+                            sfRetry 5m 10 sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || fail 206
+                            sfRetry 5m 10 sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system || fail 207
+                            sfRetry 5m 10 sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || fail 208
 
                             touch /etc/kubernetes/.joined
                             echo "init done"
@@ -347,17 +347,17 @@ feature:
                         run: |
                             case {{.CNI}} in
                                 flannel)
-                                    sfKubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml || exit 209
+                                    sfKubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml || fail 209
 
                                     sfFirewallAdd --zone=trusted --add-interface=flannel.1
                                     sfFirewallAdd --zone=trusted --add-interface=cni0
                                     sfFirewallReload || fail 204 "Firewall problem"
                                     ;;
                                 calico) # Untested yet...
-                                    sfKubectl apply -f https://gist.githubusercontent.com/joshrosso/ed1f5ea5a2f47d86f536e9eee3f1a2c2/raw/dfd95b9230fb3f75543706f3a95989964f36b154/calico-3.5.yaml || exit 210
+                                    sfKubectl apply -f https://gist.githubusercontent.com/joshrosso/ed1f5ea5a2f47d86f536e9eee3f1a2c2/raw/dfd95b9230fb3f75543706f3a95989964f36b154/calico-3.5.yaml || fail 210
                                     ;;
                                 canal) # Untested yet...
-                                    sfKubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/canal/canal.yaml || exit 211
+                                    sfKubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/canal/canal.yaml || fail 211
                                     sfFirewallAdd --zone=trusted --add-interface=cni0
                                     sfFirewallReload || fail 204 "Firewall problem"
                                     ;;
@@ -371,19 +371,19 @@ feature:
                             # Don't try to init a kubernetes cluster already running
                             [ -f /etc/kubernetes/.joined ] && exit 0
 
-                            sfDropzonePop ${SF_TMPDIR} || exit 212
+                            sfDropzonePop ${SF_TMPDIR} || fail 212
                             sfDropzoneClean
 
-                            [ -f ${SF_TMPDIR}/cp_join_cmd.sh ] || exit 213
-                            bash ${SF_TMPDIR}/cp_join_cmd.sh || exit 215
-                            [ -f ${SF_TMPDIR}/init_cluster_admin_kube.sh ] || exit 215
-                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || exit 216
+                            [ -f ${SF_TMPDIR}/cp_join_cmd.sh ] || fail 213
+                            bash ${SF_TMPDIR}/cp_join_cmd.sh || fail 215
+                            [ -f ${SF_TMPDIR}/init_cluster_admin_kube.sh ] || fail 215
+                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || fail 216
 
                             # waits availability of key pods
                             set -u -o pipefail
-                            sfRetry 5m 10 sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || exit 217
-                            sfRetry 5m 10 sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') == 'True' ]" || exit 218
-                            sfRetry 5m 10 sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || exit 219
+                            sfRetry 5m 10 sfIsPodRunning kube-apiserver-{{.Hostname}}@kube-system || fail 217
+                            sfRetry 5m 10 sfIsPodRunning kube-controller-manager-{{.Hostname}}@kube-system -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') == 'True' ]" || fail 218
+                            sfRetry 5m 10 sfIsPodRunning kube-scheduler-{{.Hostname}}@kube-system || fail 219
 
                             # Configure firewall
                             case {{.CNI}} in
@@ -416,7 +416,7 @@ feature:
                                 break
                             done
                             [ -z "$MASTERIP" ] && echo "failed to find available master to register with. Aborted." && exit 220
-                            eval $NODE_JOIN_CMD || exit 221
+                            eval $NODE_JOIN_CMD || fail 221
                             touch /etc/kubernetes/.joined
                             exit 0
 
@@ -425,10 +425,12 @@ feature:
                             masters: one
                         run: |
                             # Allows pods to start on master if there is only one master or if it's explicitely requested
-                            [ "{{.ClusterComplexity}}" = "small" -o "{{.AllowPodsOnMasters}}" = "true" ] && sfKubectl taint nodes --all node-role.kubernetes.io/master-
+                            [ "{{.ClusterComplexity}}" = "small" -o "{{.AllowPodsOnMasters}}" = "true" ] && sfKubectl taint nodes --all node-role.kubernetes.io/master- || true
                             # adds Kubernetes Dashboard
                             if [ "{{.Dashboard}}" = "true" ]; then
-                                sfRetry 3m 5 sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || exit 222
+                                if curl --output /dev/null --silent --head --fail "https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml"; then
+                                    sfRetry 3m 5 sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || fail 222 "Unable to install kubernetes dashboard"
+                                fi
                             fi
 
                             # cat <<EOF | kubectl apply -f -
@@ -484,10 +486,10 @@ feature:
                         run: |
                             case $LINUX_KIND in
                                 debian|ubuntu)
-                                    sfApt purge -y kubectl kubeadm kubelet || exit 223
+                                    sfApt purge -y kubectl kubeadm kubelet || fail 223 "Failure purging kubernetes"
                                     ;;
                                 redhat|centos)
-                                    yum remove -y kubectl kubeadm kubelet || exit 224
+                                    yum remove -y kubectl kubeadm kubelet || fail 224 "Failure purging kubernetes"
                                     ;;
                             esac
                             sfFirewallReload || fail 204 "Firewall problem"
diff --git a/features/ntpclient.yml b/features/ntpclient.yml
--- a/features/ntpclient.yml
+++ b/features/ntpclient.yml
@@ -33,10 +33,10 @@ feature:
                         run: |
                             case $LINUX_KIND in
                                 debian|ubuntu)
-                                    dpkg -l | grep ntpdate &>/dev/null || exit 1
+                                    dpkg -l | grep ntpdate &>/dev/null || fail 1
                                     ;;
                                 centos|rhel)
-                                    rpm -qa | grep ntpdate &>/dev/null || exit 1
+                                    rpm -qa | grep ntpdate &>/dev/null || fail 1
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
@@ -58,10 +58,10 @@ feature:
                                 debian|ubuntu)
                                     export DEBIAN_FRONTEND=noninteractive
                                     sfRetry 5m 3 "sfApt update"
-                                    sfRetry 5m 3 "sfApt install -y ntpdate" || exit 194
+                                    sfRetry 5m 3 "sfApt install -y ntpdate" || fail 194
                                     ;;
                                 centos|rhel)
-                                    yum install -y ntpdate || exit 194
+                                    yum install -y ntpdate || fail 194
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
@@ -78,18 +78,18 @@ feature:
                             nodes: all
                         run: |
                             echo "{{.GatewayIP}}  NTP-server-host" >> /etc/hosts
-                            ntpdate NTP-server-host || exit 201
+                            ntpdate NTP-server-host || fail 201
                             timedatectl set-ntp off
                             case $LINUX_KIND in
                                 debian|ubuntu)
                                     export DEBIAN_FRONTEND=noninteractive
-                                    sfRetry 5m 3 "sfApt install -y ntp ntpstat" || exit 202
-                                    sed -i '/^pool...ubuntu.pool.ntp.org/ s/^/#/' /etc/ntp.conf  || exit 203
-                                    sed -i '/^pool ntp.ubuntu.com/ s/^/#/' /etc/ntp.conf  || exit 204
+                                    sfRetry 5m 3 "sfApt install -y ntp ntpstat" || fail 202
+                                    sed -i '/^pool...ubuntu.pool.ntp.org/ s/^/#/' /etc/ntp.conf  || fail 203
+                                    sed -i '/^pool ntp.ubuntu.com/ s/^/#/' /etc/ntp.conf  || fail 204
                                     ;;
                                 centos|rhel)
-                                    yum install -y ntp || exit 202
-                                    sed -i '/^server...centos.pool.ntp.org/ s/^/#/' /etc/ntp.conf || exit 203
+                                    yum install -y ntp || fail 202
+                                    sed -i '/^server...centos.pool.ntp.org/ s/^/#/' /etc/ntp.conf || fail 203
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
@@ -108,15 +108,15 @@ feature:
                         run: |
                             case $LINUX_KIND in
                                 debian|ubuntu)
-                                    sfService enable ntp || exit 195
-                                    sfService restart ntp || exit 196
+                                    sfService enable ntp || fail 195
+                                    sfService restart ntp || fail 196
                                     op=-1
                                     sfRetry 5m 5 sfService status ntp &>/dev/null && op=$? || true
                                     [ $op -ne 0 ] && exit 197
                                     ;;
                                 centos|rhel)
-                                    sfService enable ntpd || exit 195
-                                    sfService restart ntpd || exit 196
+                                    sfService enable ntpd || fail 195
+                                    sfService restart ntpd || fail 196
                                     op=-1
                                     sfRetry 5m 5 sfService status ntpd &>/dev/null && op=$? || true
                                     [ $op -ne 0 ] && exit 197
