Using fail instead of exit in features

diff --git a/features/keycloak4platform.yml b/features/keycloak4platform.yml
--- a/features/keycloak4platform.yml
+++ b/features/keycloak4platform.yml
@@ -219,7 +219,7 @@ feature:
                             CMD ["-b", "0.0.0.0"]
                             EOF
 
-                            docker build --network host -t keycloak4platform:latest ${SF_ETCDIR}/keycloak4platform/build || exit 192
+                            docker build --network host -t keycloak4platform:latest ${SF_ETCDIR}/keycloak4platform/build || fail 192
                             exit 0
 
                     secret:
@@ -230,8 +230,8 @@ feature:
                             nodes: no
                         run: |
                             docker secret rm safescale.keycloak.db_password safescale.keycloak.admin_password &>/dev/null || true
-                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.keycloak.db_password - || exit 193
-                            echo -n "{{ .KeycloakAdminPassword }}" | docker secret create safescale.keycloak.admin_password - || exit 194
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.keycloak.db_password - || fail 193
+                            echo -n "{{ .KeycloakAdminPassword }}" | docker secret create safescale.keycloak.admin_password - || fail 194
                             exit 0
 
                     database:
@@ -241,8 +241,8 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            docker exec $(docker ps -q -f name=postgresxl4safescale_coordinator) psql -c "CREATE DATABASE keycloak4platform;" || exit 195
-                            docker exec $(docker ps -q -f name=postgresxl4safescale_coordinator) psql -c "CREATE USER keycloak4platform;" || exit 196
+                            docker exec $(docker ps -q -f name=postgresxl4safescale_coordinator) psql -c "CREATE DATABASE keycloak4platform;" || fail 195
+                            docker exec $(docker ps -q -f name=postgresxl4safescale_coordinator) psql -c "CREATE USER keycloak4platform;" || fail 196
                             exit 0
 
                     stack:
@@ -302,8 +302,8 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            docker stack deploy -c ${SF_ETCDIR}/keycloak4platform/stack.yml keycloak4platform || exit 197
-                            sfRetry 5m 5 "sfDoesDockerRunService keycloak4platform:latest keycloak4platform_server" || exit 198
+                            docker stack deploy -c ${SF_ETCDIR}/keycloak4platform/stack.yml keycloak4platform || fail 197
+                            sfRetry 5m 5 "sfDoesDockerRunService keycloak4platform:latest keycloak4platform_server" || fail 198
                             exit 0
 
             remove:
@@ -316,7 +316,7 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            docker stack rm keycloak4platform || exit 199
+                            docker stack rm keycloak4platform || fail 199
                             docker secret rm safescale.keycloak.db_password safescale.keycloak.admin_password &>/dev/null
                             # VPL: add database keycloak4platform deletion
                             docker exec $(docker ps -q -f name=postgresxl4safescale_coordinator) psql -c "DROP DATABASE keycloak4platform;"
diff --git a/features/postgresql4platform.yml b/features/postgresql4platform.yml
--- a/features/postgresql4platform.yml
+++ b/features/postgresql4platform.yml
@@ -35,7 +35,7 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            sfDoesDockerRunStack postgresql4platform || exit 192
+                            sfDoesDockerRunStack postgresql4platform || fail 192
                             exit 0
 
             add:
@@ -292,7 +292,7 @@ feature:
                     #         nodes: no
                     #     run: |
                     #         docker secret rm postgresql4platform &>/dev/null || true
-                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create postgresql4platform - || exit 192
+                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create postgresql4platform - || fail 192
                     #         exit 0
 
                     # network:
@@ -303,10 +303,10 @@ feature:
                     #         nodes: no
                     #     run: |
                     #         # if ! docker network list --filter 'name=safescale-gw' {{ "--format '{{.Driver}}:{{.Scope}}'" }} | grep 'overlay:swarm'; then
-                    #         #     docker network create --attachable -d overlay --scope swarm safescale-gw || exit 192
+                    #         #     docker network create --attachable -d overlay --scope swarm safescale-gw || fail 192
                     #         # fi
                     #         if ! docker network list --filter 'name=safescale-gw' | grep safescale-gw; then
-                    #             docker network create --attachable -d bridge safescale-gw || exit 193
+                    #             docker network create --attachable -d bridge safescale-gw || fail 193
                     #         fi
                     #         exit 0
 
@@ -315,16 +315,16 @@ feature:
                             masters: any
                         run: |
                             if docker secret inspect safescale.postgresql.password &>/dev/null; then
-                                docker secret rm safescale.postgresql.password || exit 192
+                                docker secret rm safescale.postgresql.password || fail 192
                             fi
-                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password - || exit 193
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password - || fail 193
 
                     start:
                         targets:
                             masters: any
                         run: |
-                            docker stack deploy -c ${SF_ETCDIR}/postgresql4platform/stack.yml postgresql4platform || exit 194
-                            sfRetry 5m 5 sfDoesDockerRunStack postgresql4platform || exit 195
+                            docker stack deploy -c ${SF_ETCDIR}/postgresql4platform/stack.yml postgresql4platform || fail 194
+                            sfRetry 5m 5 sfDoesDockerRunStack postgresql4platform || fail 195
                             exit 0
 
             remove:
@@ -335,7 +335,7 @@ feature:
                             masters: any
                         run: |
                             if [ -f ${SF_ETCDIR}/postgresql4platform/stack.yml ]; then
-                                docker stack rm postgresql4platform || exit 192
+                                docker stack rm postgresql4platform || fail 192
                             fi
                             exit 0
 
diff --git a/features/postgresxl.yml b/features/postgresxl.yml
--- a/features/postgresxl.yml
+++ b/features/postgresxl.yml
@@ -47,7 +47,7 @@ feature:
                             masters: all
                             nodes: no
                         run: |
-                            docker image ls {{ "--format '{{.Repository}}:{{.Tag}}'" }} | grep 'postgresxl:latest' || exit 192
+                            docker image ls {{ "--format '{{.Repository}}:{{.Tag}}'" }} | grep 'postgresxl:latest' || fail 192
                             exit 0
 
             add:
@@ -375,7 +375,7 @@ feature:
                             ENTRYPOINT ["/docker-entrypoint.sh"]
                             EOF
 
-                            docker build --network host --build-arg PARALLEL=$PARALLEL -t postgresxl:latest ${SF_ETCDIR}/postgresxl/build || exit 192
+                            docker build --network host --build-arg PARALLEL=$PARALLEL -t postgresxl:latest ${SF_ETCDIR}/postgresxl/build || fail 192
                             yes | docker image prune || true
                             exit 0
 
@@ -597,7 +597,7 @@ feature:
                             {{ else }}
                             PASSWORD="{{ .AdminPassword }}"
                             {{ end }}
-                            echo -n "$PASSWORD" | docker secret create postgresxl.password - || exit 193
+                            echo -n "$PASSWORD" | docker secret create postgresxl.password - || fail 193
                             exit 0
 
                     network:
@@ -630,12 +630,12 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            docker stack deploy -c ${SF_ETCDIR}/postgresxl/stack.yml postgresxl || exit 194
-                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_gtm-master" || exit 195
-                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_gtm-slave" || exit 196
-                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_gtm-proxy" || exit 197
-                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_coordinator" || exit 198
-                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_data" || exit 199
+                            docker stack deploy -c ${SF_ETCDIR}/postgresxl/stack.yml postgresxl || fail 194
+                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_gtm-master" || fail 195
+                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_gtm-slave" || fail 196
+                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_gtm-proxy" || fail 197
+                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_coordinator" || fail 198
+                            sfRetry 5m 5 "sfDoesDockerRunService postgresxl:latest postgresxl_data" || fail 199
                             exit 0
 
             remove:
@@ -648,7 +648,7 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            sfRetry 5m 5 "docker stack rm postgresxl" || exit 200
+                            sfRetry 5m 5 "docker stack rm postgresxl" || fail 200
                             exit 0
 
                     cleanup:
