Changed error handling in features

diff --git a/features/keycloak4platform.yml b/features/keycloak4platform.yml
--- a/features/keycloak4platform.yml
+++ b/features/keycloak4platform.yml
@@ -166,8 +166,9 @@ feature:
 
                             # wait for database server
                             echo "Waiting for database server..."
-                            timeout 60 bash -c "while ! $PSQL 'select 1' >/dev/null; do sleep 5; done"
-                            if [ $? -ne 0 ] && echo "Database server not ready for 60s. Aborting." && exit 1
+                            op=-1
+                            timeout 60 bash -c "while ! $PSQL 'select 1' >/dev/null; do sleep 5; done" && op=$? || true
+                            if [ $op -ne 0 ] && echo "Database server not ready for 60s. Aborting." && exit 1
                             echo "Database server ready."
 
                             # # Create database if needed
