Changes in features
- Renamed exit to sfFail

diff --git a/features/keycloak4platform.yml b/features/keycloak4platform.yml
--- a/features/keycloak4platform.yml
+++ b/features/keycloak4platform.yml
@@ -156,7 +156,13 @@ feature:
                             echo "Waiting for database server..."
                             op=-1
                             timeout 60 bash -c "while ! $PSQL 'select 1' >/dev/null; do sleep 5; done" && op=$? || true
+<<<<<<< refs/remotes/origin/develop
                             if [ $op -ne 0 ] && echo "Database server not ready for 60s. Aborting." && exit 1
+||||||| ancestor
+                            if [ $op -ne 0 ] && echo "Database server not ready for 60s. Aborting." && fail 1
+=======
+                            if [ $op -ne 0 ] && echo "Database server not ready for 60s. Aborting." && sfFail 1
+>>>>>>> Changes in features
                             echo "Database server ready."
 
                             # # Create database if needed
@@ -207,8 +213,16 @@ feature:
                             CMD ["-b", "0.0.0.0"]
                             EOF
 
+<<<<<<< refs/remotes/origin/develop
                             docker build --network host -t keycloak4platform:latest ${SF_ETCDIR}/keycloak4platform/build || exit 192
                             exit 0
+||||||| ancestor
+                            docker build --network host -t keycloak4platform:latest ${SF_ETCDIR}/keycloak4platform/build || fail 192
+                            exit 0
+=======
+                            docker build --network host -t keycloak4platform:latest ${SF_ETCDIR}/keycloak4platform/build || sfFail 192
+                            sfFail 0
+>>>>>>> Changes in features
 
                     secret:
                         targets:
@@ -218,24 +232,50 @@ feature:
                             nodes: no
                         run: |
                             docker secret rm safescale.keycloak.password.dbuser safescale.keycloak.password.admin &>/dev/null || true
+<<<<<<< refs/remotes/origin/develop
                             echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.keycloak.password.dbuser - || exit 193
                             echo -n "{{ .KeycloakAdminPassword }}" | docker secret create safescale.keycloak.password.admin - || exit 194
                             exit 0
+||||||| ancestor
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.keycloak.password.dbuser - || fail 193
+                            echo -n "{{ .KeycloakAdminPassword }}" | docker secret create safescale.keycloak.password.admin - || fail 194
+                            exit 0
+=======
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.keycloak.password.dbuser - || sfFail 193
+                            echo -n "{{ .KeycloakAdminPassword }}" | docker secret create safescale.keycloak.password.admin - || sfFail 194
+                            sfFail 0
+>>>>>>> Changes in features
 
                     pgsql:
                         targets:
                             masters: any
                         run: |
                             sfPsqlCreateDatabase keycloak4platform
+<<<<<<< refs/remotes/origin/develop
                             echo -n "{{ .KeycloakdAdminPassword }}" | sfPsqlCreateRole keycloak4platform LOGIN || exit 196
                             exit 0
+||||||| ancestor
+                            echo -n "{{ .KeycloakdAdminPassword }}" | sfPsqlCreateRole keycloak4platform LOGIN || fail 196
+                            exit 0
+=======
+                            echo -n "{{ .KeycloakdAdminPassword }}" | sfPsqlCreateRole keycloak4platform LOGIN || sfFail 196
+                            sfFail 0
+>>>>>>> Changes in features
 
                     pgpool:
                         targets:
                             masters: all
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             echo -n "{{ .KeycloakdAdminPassword }}" | sfPgpoolUpdatePassword keycloak4platform || exit 197
                             exit 0
+||||||| ancestor
+                            echo -n "{{ .KeycloakdAdminPassword }}" | sfPgpoolUpdatePassword keycloak4platform || fail 197
+                            exit 0
+=======
+                            echo -n "{{ .KeycloakdAdminPassword }}" | sfPgpoolUpdatePassword keycloak4platform || sfFail 197
+                            sfFail 0
+>>>>>>> Changes in features
 
                     stack:
                         targets:
@@ -285,9 +325,19 @@ feature:
                         targets:
                             masters: any
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             docker stack deploy -c ${SF_ETCDIR}/keycloak4platform/stack.yml keycloak4platform || exit 197
                             sfRetry 5m 5 "sfDoesDockerRunStack keycloak4platform" || exit 198
                             exit 0
+||||||| ancestor
+                            docker stack deploy -c ${SF_ETCDIR}/keycloak4platform/stack.yml keycloak4platform || fail 197
+                            sfRetry 5m 5 "sfDoesDockerRunStack keycloak4platform" || fail 198
+                            exit 0
+=======
+                            docker stack deploy -c ${SF_ETCDIR}/keycloak4platform/stack.yml keycloak4platform || sfFail 197
+                            sfRetry 5m 5 "sfDoesDockerRunStack keycloak4platform" || sfFail 198
+                            sfFail 0
+>>>>>>> Changes in features
 
             remove:
                 pace: stack,cleanup
@@ -296,12 +346,18 @@ feature:
                         targets:
                             masters: any
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             docker stack rm keycloak4platform || exit 199
+||||||| ancestor
+                            docker stack rm keycloak4platform || fail 199
+=======
+                            docker stack rm keycloak4platform || sfFail 199
+>>>>>>> Changes in features
                             docker secret rm safescale.keycloak.password.dbuser safescale.keycloak.password.admin &>/dev/null
                             # VPL: add database keycloak4platform deletion
                             sfPgsqlDropDatabase keycloak4platform
                             sfPgsqlDropRole keycloak4platform
-                            exit 0
+                            sfFail 0
 
                     cleanup:
                         targets:
@@ -312,7 +368,7 @@ feature:
                         run: |
                             sfRemoveDockerImage keycloak4platform:latest
                             rm -drf ${SF_ETCDIR}/keycloak4platform ${SF_VARDIR}/keycloak4platform
-                            exit 0
+                            sfFail 0
 
     proxy:
         rules:
diff --git a/features/kong4safescale.yml b/features/kong4safescale.yml
--- a/features/kong4safescale.yml
+++ b/features/kong4safescale.yml
@@ -70,7 +70,13 @@ feature:
                             echo "Waiting for database server..."
                             op=-1
                             timeout 60 sh -c "while ! $PSQL -c 'select 1' >/dev/null; do sleep 5; done" && op=$? || true
+<<<<<<< refs/remotes/origin/develop
                             [ $op -ne 0 ] && echo "Database exited to respond in 60s, aborting." && exit 1
+||||||| ancestor
+                            [ $op -ne 0 ] && echo "Database failed to respond in 60s, aborting." && fail 1
+=======
+                            [ $op -ne 0 ] && echo "Database exited to respond in 60s, aborting." && sfFail 1
+>>>>>>> Changes in features
                             echo "Database server ready."
 
                             case \$1 in
@@ -83,7 +89,7 @@ feature:
                                         # $PSQL "CREATE DATABASE kong4safescale-gui;"
                                         echo Done
                                     fi
-                                    exit 0
+                                    sfFail 0
                                     ;;
 
                                 proxy)
@@ -112,7 +118,7 @@ feature:
                             esac
 
                             echo "Neither 'dbinit' nor 'proxy' parameter provided, stopping.""
-                            exit 0
+                            sfFail 0
                             EOF
 
                             # cat >${SF_ETCDIR}/kong4safescale/konga.userdb.data <<-EOF
@@ -171,8 +177,16 @@ feature:
 
                             CMD ["kong", "docker-start"]
                             EOF
+<<<<<<< refs/remotes/origin/develop
                             docker build --network host -t kong4safescale:latest ${SF_ETCDIR}/kong4safescale/build || exit 192
                             exit 0
+||||||| ancestor
+                            docker build --network host -t kong4safescale:latest ${SF_ETCDIR}/kong4safescale/build || fail 192
+                            exit 0
+=======
+                            docker build --network host -t kong4safescale:latest ${SF_ETCDIR}/kong4safescale/build || sfFail 192
+                            sfFail 0
+>>>>>>> Changes in features
 
                     stack:
                         targets:
@@ -233,7 +247,13 @@ feature:
                                             max_attempts: 3
                                             window: 120s
                                     # healthcheck:
+<<<<<<< refs/remotes/origin/develop
                                     #     test: ["CMD-SHELL", "curl -I -s -k -L https://127.0.0.1:8444 || exit 1"]
+||||||| ancestor
+                                    #     test: ["CMD-SHELL", "curl -I -s -k -L https://127.0.0.1:8444 || fail 1"]
+=======
+                                    #     test: ["CMD-SHELL", "curl -I -s -k -L https://127.0.0.1:8444 || sfFail 1"]
+>>>>>>> Changes in features
                                     #     interval: 5s
                                     #     retries: 10
                                     secrets:
@@ -282,7 +302,7 @@ feature:
                                 #             window: 120s
 
                             chmod go-rwx ${SF_ETCDIR}/kong4safescale/stack.yml
-                            exit 0
+                            sfFail 0
 
                     secret:
                         targets:
@@ -292,8 +312,16 @@ feature:
                             nodes: no
                         run: |
                             docker secret rm safescale.kong.db_password &>/dev/null || true
+<<<<<<< refs/remotes/origin/develop
                             echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.kong.db_password - &>/dev/null || exit 193
                             exit 0
+||||||| ancestor
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.kong.db_password - &>/dev/null || fail 193
+                            exit 0
+=======
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.kong.db_password - &>/dev/null || sfFail 193
+                            sfFail 0
+>>>>>>> Changes in features
 
                     start:
                         targets:
@@ -302,9 +330,19 @@ feature:
                             masters: any
                             nodes: no
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             docker stack deploy -c ${SF_ETCDIR}/kong4safescale/stack.yml kong4safescale || exit 194
                             sfRetry 5m 5 "sfDoesDockerRunService kong4safescale:latest kong4safescale_proxy" || exit 195
                             exit 0
+||||||| ancestor
+                            docker stack deploy -c ${SF_ETCDIR}/kong4safescale/stack.yml kong4safescale || fail 194
+                            sfRetry 5m 5 "sfDoesDockerRunService kong4safescale:latest kong4safescale_proxy" || fail 195
+                            exit 0
+=======
+                            docker stack deploy -c ${SF_ETCDIR}/kong4safescale/stack.yml kong4safescale || sfFail 194
+                            sfRetry 5m 5 "sfDoesDockerRunService kong4safescale:latest kong4safescale_proxy" || sfFail 195
+                            sfFail 0
+>>>>>>> Changes in features
 
             remove:
                 pace: stop,cleanup
@@ -316,9 +354,15 @@ feature:
                             masters: any
                             nodes: no
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             docker stack rm kong4safescale  || exit 196
+||||||| ancestor
+                            docker stack rm kong4safescale  || fail 196
+=======
+                            docker stack rm kong4safescale  || sfFail 196
+>>>>>>> Changes in features
                             docker secret rm safescale.kong.db_password &>/dev/null
-                            exit 0
+                            sfFail 0
 
                     cleanup:
                         targets:
@@ -329,6 +373,6 @@ feature:
                         run: |
                             sfRemoveDockerImage kong4gateway:latest
                             rm -rf ${SF_ETCDIR}/kong4safescale
-                            exit 0
+                            sfFail 0
 
 ...
diff --git a/features/ntpclient.yml b/features/ntpclient.yml
--- a/features/ntpclient.yml
+++ b/features/ntpclient.yml
@@ -33,14 +33,32 @@ feature:
                         run: |
                             case $LINUX_KIND in
                                 debian|ubuntu)
+<<<<<<< refs/remotes/origin/develop
                                     dpkg -l | grep ntpdate &>/dev/null || exit 1
+||||||| ancestor
+                                    dpkg -l | grep ntpdate &>/dev/null || fail 1
+=======
+                                    dpkg -l | grep ntpdate &>/dev/null || sfFail 1
+>>>>>>> Changes in features
                                     ;;
                                 centos|rhel)
+<<<<<<< refs/remotes/origin/develop
                                     rpm -qa | grep ntpdate &>/dev/null || exit 1
+||||||| ancestor
+                                    rpm -qa | grep ntpdate &>/dev/null || fail 1
+=======
+                                    rpm -qa | grep ntpdate &>/dev/null || sfFail 1
+>>>>>>> Changes in features
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
+<<<<<<< refs/remotes/origin/develop
                                     exit 1
+||||||| ancestor
+                                    fail 1
+=======
+                                    sfFail 1
+>>>>>>> Changes in features
                                     ;;
                             esac
 
@@ -58,17 +76,35 @@ feature:
                                 debian|ubuntu)
                                     export DEBIAN_FRONTEND=noninteractive
                                     sfRetry 5m 3 "sfApt update"
+<<<<<<< refs/remotes/origin/develop
                                     sfRetry 5m 3 "sfApt install -y ntpdate" || exit 194
+||||||| ancestor
+                                    sfRetry 5m 3 "sfApt install -y ntpdate" || fail 194
+=======
+                                    sfRetry 5m 3 "sfApt install -y ntpdate" || sfFail 194
+>>>>>>> Changes in features
                                     ;;
                                 centos|rhel)
+<<<<<<< refs/remotes/origin/develop
                                     yum install -y ntpdate || exit 194
+||||||| ancestor
+                                    yum install -y ntpdate || fail 194
+=======
+                                    yum install -y ntpdate || sfFail 194
+>>>>>>> Changes in features
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
+<<<<<<< refs/remotes/origin/develop
                                     exit 195
+||||||| ancestor
+                                    fail 195
+=======
+                                    sfFail 195
+>>>>>>> Changes in features
                                     ;;
                             esac
-                            exit 0
+                            sfFail 0
 
                     config:
                         targets:
@@ -78,26 +114,56 @@ feature:
                             nodes: all
                         run: |
                             echo "{{.GatewayIP}}  NTP-server-host" >> /etc/hosts
+<<<<<<< refs/remotes/origin/develop
                             ntpdate NTP-server-host || exit 201
+||||||| ancestor
+                            ntpdate NTP-server-host || fail 201
+=======
+                            ntpdate NTP-server-host || sfFail 201
+>>>>>>> Changes in features
                             timedatectl set-ntp off
                             case $LINUX_KIND in
                                 debian|ubuntu)
                                     export DEBIAN_FRONTEND=noninteractive
+<<<<<<< refs/remotes/origin/develop
                                     sfRetry 5m 3 "sfApt install -y ntp ntpstat" || exit 202
                                     sed -i '/^pool...ubuntu.pool.ntp.org/ s/^/#/' /etc/ntp.conf  || exit 203
                                     sed -i '/^pool ntp.ubuntu.com/ s/^/#/' /etc/ntp.conf  || exit 204
+||||||| ancestor
+                                    sfRetry 5m 3 "sfApt install -y ntp ntpstat" || fail 202
+                                    sed -i '/^pool...ubuntu.pool.ntp.org/ s/^/#/' /etc/ntp.conf  || fail 203
+                                    sed -i '/^pool ntp.ubuntu.com/ s/^/#/' /etc/ntp.conf  || fail 204
+=======
+                                    sfRetry 5m 3 "sfApt install -y ntp ntpstat" || sfFail 202
+                                    sed -i '/^pool...ubuntu.pool.ntp.org/ s/^/#/' /etc/ntp.conf  || sfFail 203
+                                    sed -i '/^pool ntp.ubuntu.com/ s/^/#/' /etc/ntp.conf  || sfFail 204
+>>>>>>> Changes in features
                                     ;;
                                 centos|rhel)
+<<<<<<< refs/remotes/origin/develop
                                     yum install -y ntp || exit 202
                                     sed -i '/^server...centos.pool.ntp.org/ s/^/#/' /etc/ntp.conf || exit 203
+||||||| ancestor
+                                    yum install -y ntp || fail 202
+                                    sed -i '/^server...centos.pool.ntp.org/ s/^/#/' /etc/ntp.conf || fail 203
+=======
+                                    yum install -y ntp || sfFail 202
+                                    sed -i '/^server...centos.pool.ntp.org/ s/^/#/' /etc/ntp.conf || sfFail 203
+>>>>>>> Changes in features
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
+<<<<<<< refs/remotes/origin/develop
                                     exit 195
+||||||| ancestor
+                                    fail 195
+=======
+                                    sfFail 195
+>>>>>>> Changes in features
                                     ;;
                             esac
                             echo "server NTP-server-host prefer iburst" >> /etc/ntp.conf
-                            exit 0
+                            sfFail 0
 
                     ready:
                         targets:
@@ -108,25 +174,59 @@ feature:
                         run: |
                             case $LINUX_KIND in
                                 debian|ubuntu)
+<<<<<<< refs/remotes/origin/develop
                                     sfService enable ntp || exit 195
                                     sfService restart ntp || exit 196
+||||||| ancestor
+                                    sfService enable ntp || fail 195
+                                    sfService restart ntp || fail 196
+=======
+                                    sfService enable ntp || sfFail 195
+                                    sfService restart ntp || sfFail 196
+>>>>>>> Changes in features
                                     op=-1
                                     sfRetry 5m 5 sfService status ntp &>/dev/null && op=$? || true
+<<<<<<< refs/remotes/origin/develop
                                     [ $op -ne 0 ] && exit 197
+||||||| ancestor
+                                    [ $op -ne 0 ] && fail 197
+=======
+                                    [ $op -ne 0 ] && sfFail 197
+>>>>>>> Changes in features
                                     ;;
                                 centos|rhel)
+<<<<<<< refs/remotes/origin/develop
                                     sfService enable ntpd || exit 195
                                     sfService restart ntpd || exit 196
+||||||| ancestor
+                                    sfService enable ntpd || fail 195
+                                    sfService restart ntpd || fail 196
+=======
+                                    sfService enable ntpd || sfFail 195
+                                    sfService restart ntpd || sfFail 196
+>>>>>>> Changes in features
                                     op=-1
                                     sfRetry 5m 5 sfService status ntpd &>/dev/null && op=$? || true
+<<<<<<< refs/remotes/origin/develop
                                     [ $op -ne 0 ] && exit 197
+||||||| ancestor
+                                    [ $op -ne 0 ] && fail 197
+=======
+                                    [ $op -ne 0 ] && sfFail 197
+>>>>>>> Changes in features
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
+<<<<<<< refs/remotes/origin/develop
                                     exit 195
+||||||| ancestor
+                                    fail 195
+=======
+                                    sfFail 195
+>>>>>>> Changes in features
                                     ;;
                             esac
-                            exit 0
+                            sfFail 0
 
             remove:
                 pace: ntpdate
@@ -149,7 +249,13 @@ feature:
                                     ;;
                                 *)
                                     echo "Unsupported operating system '$LINUX_KIND'"
+<<<<<<< refs/remotes/origin/develop
                                     exit 1
+||||||| ancestor
+                                    fail 1
+=======
+                                    sfFail 1
+>>>>>>> Changes in features
                                     ;;
                             esac
 
diff --git a/features/postgres4gateway.yml b/features/postgres4gateway.yml
--- a/features/postgres4gateway.yml
+++ b/features/postgres4gateway.yml
@@ -38,8 +38,16 @@ feature:
                             masters: no
                             nodes: no
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             sfDoesDockerRunContainer postgres:11-alpine postgres4gateway_postgres_1 || exit 192
                             exit 0
+||||||| ancestor
+                            sfDoesDockerRunContainer postgres:11-alpine postgres4gateway_postgres_1 || fail 192
+                            exit 0
+=======
+                            sfDoesDockerRunContainer postgres:11-alpine postgres4gateway_postgres_1 || sfFail 192
+                            sfFail 0
+>>>>>>> Changes in features
 
             add:
                 # pace: config,secret,network,start
@@ -92,7 +100,7 @@ feature:
                             #         external: true
                             EOF
                             chmod go-rwx ${SF_ETCDIR}/postgres4gateway/docker-compose.yml
-                            exit 0
+                            sfFail 0
 
                     # secret:
                     #     targets:
@@ -102,8 +110,16 @@ feature:
                     #         nodes: no
                     #     run: |
                     #         docker secret rm postgres4gateway &>/dev/null || true
+<<<<<<< refs/remotes/origin/develop
                     #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create postgres4gateway - || exit 192
                     #         exit 0
+||||||| ancestor
+                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create postgres4gateway - || fail 192
+                    #         exit 0
+=======
+                    #         echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create postgres4gateway - || sfFail 192
+                    #         sfFail 0
+>>>>>>> Changes in features
 
                     # network:
                     #     targets:
@@ -113,12 +129,24 @@ feature:
                     #         nodes: no
                     #     run: |
                     #         # if ! docker network list --filter 'name=safescale-gw' {{ "--format '{{.Driver}}:{{.Scope}}'" }} | grep 'overlay:swarm'; then
+<<<<<<< refs/remotes/origin/develop
                     #         #     docker network create --attachable -d overlay --scope swarm safescale-gw || exit 192
+||||||| ancestor
+                    #         #     docker network create --attachable -d overlay --scope swarm safescale-gw || fail 192
+=======
+                    #         #     docker network create --attachable -d overlay --scope swarm safescale-gw || sfFail 192
+>>>>>>> Changes in features
                     #         # fi
                     #         if ! docker network list --filter 'name=safescale-gw' | grep safescale-gw; then
+<<<<<<< refs/remotes/origin/develop
                     #             docker network create --attachable -d bridge safescale-gw || exit 193
+||||||| ancestor
+                    #             docker network create --attachable -d bridge safescale-gw || fail 193
+=======
+                    #             docker network create --attachable -d bridge safescale-gw || sfFail 193
+>>>>>>> Changes in features
                     #         fi
-                    #         exit 0
+                    #         sfFail 0
 
                     start:
                         targets:
@@ -127,9 +155,19 @@ feature:
                             masters: no
                             nodes: no
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             docker-compose -f ${SF_ETCDIR}/postgres4gateway/docker-compose.yml -p postgres4gateway up -d || exit 194
                             sfRetry 5m 5 "sfDoesDockerRunContainer postgres:11-alpine postgres4gateway_postgres_1" || exit 195
                             exit 0
+||||||| ancestor
+                            docker-compose -f ${SF_ETCDIR}/postgres4gateway/docker-compose.yml -p postgres4gateway up -d || fail 194
+                            sfRetry 5m 5 "sfDoesDockerRunContainer postgres:11-alpine postgres4gateway_postgres_1" || fail 195
+                            exit 0
+=======
+                            docker-compose -f ${SF_ETCDIR}/postgres4gateway/docker-compose.yml -p postgres4gateway up -d || sfFail 194
+                            sfRetry 5m 5 "sfDoesDockerRunContainer postgres:11-alpine postgres4gateway_postgres_1" || sfFail 195
+                            sfFail 0
+>>>>>>> Changes in features
 
             remove:
                 pace: compose,cleanup
@@ -141,10 +179,16 @@ feature:
                             masters: no
                             nodes: no
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             docker-compose -f ${SF_ETCDIR}/postgres4gateway/docker-compose.yml -p postgres4gateway rm --stop --force || exit 196
+||||||| ancestor
+                            docker-compose -f ${SF_ETCDIR}/postgres4gateway/docker-compose.yml -p postgres4gateway rm --stop --force || fail 196
+=======
+                            docker-compose -f ${SF_ETCDIR}/postgres4gateway/docker-compose.yml -p postgres4gateway rm --stop --force || sfFail 196
+>>>>>>> Changes in features
                             docker image rm -f postgres:11-alpine
                             # docker secret rm postgres4gateway &>/dev/null
-                            exit 0
+                            sfFail 0
 
                     cleanup:
                         targets:
@@ -157,6 +201,6 @@ feature:
                             if [ "${PURGE_ON_REMOVAL,,}" = "yes" ]; then
                                 rm -rf ${SF_ETCDIR}/postgres4gateway ${SF_VARDIR}/postgres4gateway
                             fi
-                            exit 0
+                            sfFail 0
 
 ...
diff --git a/features/postgresql4platform.yml b/features/postgresql4platform.yml
--- a/features/postgresql4platform.yml
+++ b/features/postgresql4platform.yml
@@ -35,8 +35,16 @@ feature:
                             masters: any
                             nodes: no
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             sfDoesDockerRunStack postgresql4platform || exit 192
                             exit 0
+||||||| ancestor
+                            sfDoesDockerRunStack postgresql4platform || fail 192
+                            exit 0
+=======
+                            sfDoesDockerRunStack postgresql4platform || sfFail 192
+                            sfFail 0
+>>>>>>> Changes in features
 
             add:
                 pace: network,pgsql-cfg,pgsql-img,pgpool-cfg,pgpool-img,reverseproxy,secrets,stack,start
@@ -140,7 +148,7 @@ feature:
                             service_reload_command='pg_ctl -D /var/lib/postgresql/data reload'
                             EOF
                             chown 70:safescale ${SF_ETCDIR}/postgresql4platform/repmgr.conf
-                            exit 0
+                            sfFail 0
 
                     pgpool-cfg:
                         targets:
@@ -205,7 +213,7 @@ feature:
                             done
                             chown 70:safescale ${SF_ETCDIR}/postgresql4platform/pgpool.conf.template
                             chmod u+rw-x,g+r-wx,o-rwx ${SF_ETCDIR}/postgresql4platform/pgpool.conf.template
-                            exit 0
+                            sfFail 0
 
                     pgsql-img:
                         targets:
@@ -268,9 +276,19 @@ feature:
                                 echo -n "Waiting postgresql master is ready... "
                                 update_postgresql_conf
                                 update_pghba_conf
+                                pg_ctl start &>/dev/null && wait_for_local_postgres 60
+                                [ \$? -ne 0 ] && echo "Failed." && sfFail 1
                                 op=-1
+<<<<<<< refs/remotes/origin/develop
                                 pg_ctl start &>/dev/null && wait_for_local_postgres 60 && op=$?
                                 [ $op -ne 0 ] && echo "exited." && exit 1
+||||||| ancestor
+                                pg_ctl start &>/dev/null && wait_for_local_postgres 60 && op=$?
+                                [ $op -ne 0 ] && echo "Failed." && fail 1
+=======
+                                pg_ctl start &>/dev/null && wait_for_local_postgres 60 && op=\$?
+                                [ \$op -ne 0 ] && echo "Failed." && sfFail 1
+>>>>>>> Changes in features
                                 echo OK
 
                                 # Checking if repmgr needs to be initialized
@@ -289,17 +307,35 @@ feature:
 
                                     echo -n "registering host as primary postgresql instance... "
                                     op=-1
+<<<<<<< refs/remotes/origin/develop
                                     repmgr --config-file=/etc/postgresql/repmgr.conf primary register && op=$?
                                     [ $op -ne 0 ] && echo "exited." && exit 2
                                     echo done
+||||||| ancestor
+                                    repmgr --config-file=/etc/postgresql/repmgr.conf primary register && op=$?
+                                    [ $op -ne 0 ] && echo "Failed." && fail 2
+                                    echo done
+=======
+                                    repmgr --config-file=/etc/postgresql/repmgr.conf primary register && op=\$?
+                                    [ \$op -ne 0 ] && echo "Failed." && sfFail 2
+>>>>>>> Changes in features
                                 fi
                                 pg_ctl stop -m fast &>/dev/null
                             else
                                 # We are on a slave
                                 echo -n "Waiting postgresql master is ready... "
+<<<<<<< refs/remotes/origin/develop
                                 op=-1
                                 wait_for_dbmaster 60 && op=$?
                                 [ $op -ne 0 ] && echo exited && exit 3
+||||||| ancestor
+                                op=-1
+                                wait_for_dbmaster 60 && op=$?
+                                [ $op -ne 0 ] && echo Failed && fail 3
+=======
+                                wait_for_dbmaster 60
+                                [ \$? -ne 0 ] && echo Failed && sfFail 3
+>>>>>>> Changes in features
                                 echo OK
                                 registered=\$(psql -qAt -h "\$REPMGR_PRIMARY_HOST" -U repmgr repmgr -c "SELECT 1 FROM repmgr.nodes WHERE node_id=\${nodeid}")
                                 if [ "\$registered" != "1" ]; then
@@ -311,12 +347,28 @@ feature:
                                     update_postgresql_conf
                                     update_pghba_conf
                                     op=-1
+<<<<<<< refs/remotes/origin/develop
                                     pg_ctl start &>/dev/stdout && wait_for_local_postgres 60 && op=$?
                                     [ $op -ne 0 ] && echo "exited to start postgresql instance." && exit 4
+||||||| ancestor
+                                    pg_ctl start &>/dev/stdout && wait_for_local_postgres 60 && op=$?
+                                    [ $op -ne 0 ] && echo "Failed to start postgresql instance." && fail 4
+=======
+                                    pg_ctl start &>/dev/stdout && wait_for_local_postgres 60 && op=\$?
+                                    [ \$op -ne 0 ] && echo "exited to start postgresql instance." && sfFail 4
+>>>>>>> Changes in features
                                     echo -n "Registering postgresql instance as hot-standby... "
                                     op=-1
+<<<<<<< refs/remotes/origin/develop
                                     repmgr --config-file=/etc/postgresql/repmgr.conf --host="\$REPMGR_PRIMARY_HOST" --username=repmgr --dbname=repmgr standby register && op=$?
                                     [ $op -ne 0 ] && echo "exited." && exit 5
+||||||| ancestor
+                                    repmgr --config-file=/etc/postgresql/repmgr.conf --host="\$REPMGR_PRIMARY_HOST" --username=repmgr --dbname=repmgr standby register && op=$?
+                                    [ $op -ne 0 ] && echo "Failed." && fail 5
+=======
+                                    repmgr --config-file=/etc/postgresql/repmgr.conf --host="\$REPMGR_PRIMARY_HOST" --username=repmgr --dbname=repmgr standby register && op=\$?
+                                    [ \$op -ne 0 ] && echo "exited." && sfFail 5
+>>>>>>> Changes in features
                                     echo done
                                 fi
                             fi
@@ -360,7 +412,13 @@ feature:
                             #if [ \$designated_master_count -lt 1 ]; then
                             #    echo "Postgresql cluster is in inconsistent state:"
                             #    echo "no primary instance registered!"
+<<<<<<< refs/remotes/origin/develop
                             #    exit 40
+||||||| ancestor
+                            #    fail 40
+=======
+                            #    sfFail 40
+>>>>>>> Changes in features
                             #fi
                             ## A new loop to find if there is at least 2 dbhosts with the same count of master role (which can't be
                             ## automatically mitigated)
@@ -422,8 +480,16 @@ feature:
                             CMD ["postgres"]
                             EOF
 
+<<<<<<< refs/remotes/origin/develop
                             docker build --network host -t pgsql4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgsql || exit 192
                             exit 0
+||||||| ancestor
+                            docker build --network host -t pgsql4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgsql || fail 192
+                            exit 0
+=======
+                            docker build --network host -t pgsql4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgsql || sfFail 192
+                            sfFail 0
+>>>>>>> Changes in features
 
                     pgpool-img:
                         targets:
@@ -433,7 +499,13 @@ feature:
 
                             cat >${SF_ETCDIR}/postgresql4platform/build/pgpool/update_password.sh <<-EOF
                             #!/bin/bash
+<<<<<<< refs/remotes/origin/develop
                             [ \$# -ne 2 ] && echo "invalid parameters" && exit 1
+||||||| ancestor
+                            [ \$# -ne 2 ] && echo "invalid parameters" && fail 1
+=======
+                            [ \$# -ne 2 ] && echo "invalid parameters" && sfFail 1
+>>>>>>> Changes in features
 
                             USERNAME=\$1
                             PASSWORD="\$2"
@@ -443,7 +515,7 @@ feature:
                             cat /tmp/pool_passwd.new >>/etc/postgresql/pool_passwd
                             rm /tmp/pool_passwd.new
                             pg_md5 --config-file=/etc/postgresql/pgpool.conf -m --username=\$USERNAME "\$PASSWORD"
-                            exit \$?
+                            sfFail \$?
                             EOF
 
                             cat >${SF_ETCDIR}/postgresql4platform/build/pgpool/my-docker-entrypoint.sh <<-EOF
@@ -487,8 +559,16 @@ feature:
                             ENTRYPOINT ["/sbin/tini", "--", "/my-docker-entrypoint.sh"]
                             EOF
 
+<<<<<<< refs/remotes/origin/develop
                             docker build --network host -t pgpool4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgpool || exit 192
                             exit 0
+||||||| ancestor
+                            docker build --network host -t pgpool4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgpool || fail 192
+                            exit 0
+=======
+                            docker build --network host -t pgpool4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgpool || sfFail 192
+                            sfFail 0
+>>>>>>> Changes in features
 
                     stack:
                         targets:
@@ -662,7 +742,7 @@ feature:
                             EOF
                             fi
                                 chmod go-rwx ${SF_ETCDIR}/postgresql4platform/stack.yml
-                            exit 0
+                            sfFail 0
 
                     reverseproxy:
                         targets:
@@ -673,7 +753,13 @@ feature:
                             elif [ -d ${SF_ETCDIR}/kong4gateway ]; then
                                 TARGET_DIR=${SF_ETCDIR}/kong4gateway
                             fi
+<<<<<<< refs/remotes/origin/develop
                             [ -z "${TARGET_DIR+x}" ] && exit 197
+||||||| ancestor
+                            [ -z "${TARGET_DIR+x}" ] && fail 197
+=======
+                            [ -z "${TARGET_DIR+x}" ] && sfFail 197
+>>>>>>> Changes in features
 
                             cat >${TARGET_DIR}/includes/postgresql4platform.conf <<-'EOF'
                             upstream postgresql4platform {
@@ -687,38 +773,80 @@ feature:
                             }
                             EOF
                             sfReverseProxyReload
-                            exit 0
+                            sfFail 0
 
                     network:
                         targets:
                             masters: any
                         run: |
                             if ! docker network list --filter 'name=postgresql4platform_net' | grep postgresql4platform_net; then
+<<<<<<< refs/remotes/origin/develop
                                 docker network create --attachable -d overlay --scope swarm postgresql4platform_net || exit 193
+||||||| ancestor
+                                docker network create --attachable -d overlay --scope swarm postgresql4platform_net || fail 193
+=======
+                                docker network create --attachable -d overlay --scope swarm postgresql4platform_net || sfFail 193
+>>>>>>> Changes in features
                             fi
-                            exit 0
+                            sfFail 0
 
                     secrets:
                         targets:
                             masters: any
                         run: |
                             if docker secret inspect safescale.postgresql.password.password.postgres &>/dev/null; then
+<<<<<<< refs/remotes/origin/develop
                                 docker secret rm safescale.postgresql.password.postgres || exit 193
+||||||| ancestor
+                                docker secret rm safescale.postgresql.password.postgres || fail 193
+=======
+                                docker secret rm safescale.postgresql.password.postgres || sfFail 193
+>>>>>>> Changes in features
                             fi
+<<<<<<< refs/remotes/origin/develop
                             echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.postgres - || exit 194
+||||||| ancestor
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.postgres - || fail 194
+=======
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.postgres - || sfFail 194
+>>>>>>> Changes in features
                             if docker secret inspect safescale.postgresql.password.repmgr &>/dev/null; then
+<<<<<<< refs/remotes/origin/develop
                                 docker secret rm safescale.postgresql.password.repmgr || exit 195
+||||||| ancestor
+                                docker secret rm safescale.postgresql.password.repmgr || fail 195
+=======
+                                docker secret rm safescale.postgresql.password.repmgr || sfFail 195
+>>>>>>> Changes in features
                             fi
+<<<<<<< refs/remotes/origin/develop
                             echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.repmgr - || exit 196
                             exit 0
+||||||| ancestor
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.repmgr - || fail 196
+                            exit 0
+=======
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.repmgr - || sfFail 196
+                            sfFail 0
+>>>>>>> Changes in features
 
                     start:
                         targets:
                             masters: any
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             docker stack deploy -c ${SF_ETCDIR}/postgresql4platform/stack.yml postgresql4platform || exit 194
                             sfRetry 5m 5 sfDoesDockerRunStack postgresql4platform || exit 195
                             exit 0
+||||||| ancestor
+                            docker stack deploy -c ${SF_ETCDIR}/postgresql4platform/stack.yml postgresql4platform || fail 194
+                            sfRetry 5m 5 sfDoesDockerRunStack postgresql4platform || fail 195
+                            exit 0
+=======
+                            docker stack deploy -c ${SF_ETCDIR}/postgresql4platform/stack.yml postgresql4platform || sfFail 197
+                            sfRetry 5m 5 sfDoesDockerRunStack postgresql4platform || sfFail 198
+                            sfFail 0
+>>>>>>> Changes in features
 
             remove:
                 pace: stack,cleanup
@@ -728,9 +856,15 @@ feature:
                             masters: any
                         run: |
                             if [ -f ${SF_ETCDIR}/postgresql4platform/stack.yml ]; then
+<<<<<<< refs/remotes/origin/develop
                                 docker stack rm postgresql4platform || exit 192
+||||||| ancestor
+                                docker stack rm postgresql4platform || fail 192
+=======
+                                docker stack rm postgresql4platform || sfFail 192
+>>>>>>> Changes in features
                             fi
-                            exit 0
+                            sfFail 0
 
                     cleanup:
                         targets:
@@ -744,6 +878,6 @@ feature:
                             if [ "${PURGE_ON_REMOVAL,,}" = "yes" -o "${PURGE_ON_REMOVAL,,}" = "true" ]; then
                                 rm -rf ${SF_ETCDIR}/postgresql4platform ${SF_VARDIR}/postgresql4platform
                             fi
-                            exit 0
+                            sfFail 0
 
 ...
