Changed error handling in features

diff --git a/features/kong4safescale.yml b/features/kong4safescale.yml
--- a/features/kong4safescale.yml
+++ b/features/kong4safescale.yml
@@ -68,8 +68,9 @@ feature:
 
                             # wait for database server
                             echo "Waiting for database server..."
-                            timeout 60 sh -c "while ! $PSQL -c 'select 1' >/dev/null; do sleep 5; done"
-                            [ $? -ne 0 ] && echo "Database failed to respond in 60s, aborting." && exit 1
+                            op=-1
+                            timeout 60 sh -c "while ! $PSQL -c 'select 1' >/dev/null; do sleep 5; done" && op=$? || true
+                            [ $op -ne 0 ] && echo "Database failed to respond in 60s, aborting." && exit 1
                             echo "Database server ready."
 
                             case \$1 in
diff --git a/features/monitoring4platform.yml b/features/monitoring4platform.yml
--- a/features/monitoring4platform.yml
+++ b/features/monitoring4platform.yml
@@ -260,11 +260,10 @@ feature:
                                 sleep 1
 
                                 tenant=$(cat /etc/safescale/tenants.json | jq -r .tenants[0].name)
-                                safescale tenant set $tenant
-                                retcode=$?
+                                retcode=-1
+                                safescale tenant set $tenant && retcode=$? || true
                                 if [ $retcode -eq 0 ]; then
-                                    result=$(safescale host reboot $1)
-                                    retcode=$?
+                                    result=$(safescale host reboot $1) && retcode=$? || true
                                     if [ $retcode -eq 0 ]; then
                                         status=$(echo $result | jq -r .status)
                                         if [ "$status" != "success" ]; then
@@ -289,8 +288,9 @@ feature:
                                         var="AMX_ALERT_${i}_LABEL_service"
                                         host=${!var}
                                         echo "Alert 'gateway_down' received for gateway '$host'. Restarting gateway '$host'..."
-                                        restart_host "$host"
-                                        [ $? -eq 0 ] && echo "Gateway '$host' restarted." || echo "failed to restart gateway '$host'!"
+                                        op=-1
+                                        restart_host "$host" && op=$? || true
+                                        [ $op -eq 0 ] && echo "Gateway '$host' restarted." || echo "failed to restart gateway '$host'!"
                                         ;;
                                     *)
                                         echo "Unknown alert '$alert' received."
