Improved feature kubernetes
- added parameter CNI to choose CNI to use (flannel,canal available currenty, the latter is not tested yet)
- moved step sysconf at first
- moved system configuration from step common-tools to sysconf
- replaced systemctl by sfService
- Fixed nginx configuration file for reverseproxy
- fixed incorrect subnet for pods
- replaced kubectl by sfKubectl as soon as cluster admin user is configured to access kubernetes cluster
- Fixed invalid variable used for cluster  complexity (ClusterComplexity instead of just Complexity)

diff --git a/features/kubernetes.yml b/features/kubernetes.yml
--- a/features/kubernetes.yml
+++ b/features/kubernetes.yml
@@ -51,6 +51,7 @@ feature:
                     minPrivateNodes: 8
     parameters:
         - AllowPodsOnMasters=false
+        - CNI=flannel
 
     install:
         dcos:
@@ -158,7 +159,7 @@ feature:
 
             add:
                 # pace: cp-dir,common-tools,sysconf,kubelet,cp1-init,cpx-init,join,weavenet,final
-                pace: common-tools,sysconf,reverseproxy,cp1-init,cni,cpx-init,join,final
+                pace: sysconf,common-tools,reverseproxy,cp1-init,cni,cpx-init,join,final
                 steps:
                     common-tools:
                         targets:
@@ -176,7 +177,6 @@ feature:
                             EOF
                                     sfApt update && sfApt install -y kubelet kubeadm kubectl || exit 192
                                     apt-mark hold kubelet kubeadm kubectl
-                                    systemctl enable --now kubelet
                                     ;;
 
                                 centos|redhat)
@@ -191,24 +191,13 @@ feature:
                                         exclude=kube*
                             EOF
 
-                                    cat >/etc/sysctl.d/k8s.conf <<EOF
-                                        net.bridge.bridge-nf-call-ip6tables = 1
-                                        net.bridge.bridge-nf-call-iptables = 1
-                            EOF
-                                    modprobe br_netfilter &>/dev/null
-                                    sysctl --system
-
-                                    # Set SELinux in permissive mode (effectively disabling it)
-                                    setenforce 0
-                                    sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
-
                                     yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes || exit 192
-                                    systemctl enable --now kubelet
                                     ;;
 
                                 *) echo "unsupported linux distribution ''"
                                    exit 193
                             esac
+                            sfService enable kubelet && sfService start kubelet
                             exit 0
 
                     sysconf:
@@ -222,10 +211,20 @@ feature:
                             case $LINUX_KIND in
                                 debian|ubuntu)
                                     sfWaitForApt
-                                    sfRetry 5m 5 apt install -y ebtables socat || exit 194
+                                    sfRetry 5m 5 sfAapt install -y ebtables socat || exit 194
                                     ;;
                                 redhat|centos)
                                     sfRetry 5m 5 yum install -y ebtables socat || exit 195
+                                    cat >/etc/sysctl.d/kubernetes.conf <<-'EOF'
+                                        net.bridge.bridge-nf-call-ip6tables = 1
+                                        net.bridge.bridge-nf-call-iptables = 1
+                            EOF
+                                    modprobe br_netfilter &>/dev/null
+                                    sysctl --system
+
+                                    # Set SELinux in permissive mode (effectively disabling it)
+                                    setenforce 0
+                                    sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
                                     ;;
                                 *)
                                     echo "Unmanaged Linux distribution '$LINUX_KIND'"
@@ -240,26 +239,25 @@ feature:
                             done
 
                             echo "net.ipv4.ip_forward=1" >>/etc/sysctl.d/99-sysctl.conf
-                            sysctl -p
+                            sysctl --system
 
                     reverseproxy:
                         targets:
                             gateways: all
                         run: |
                             cat >${SF_ETCDIR}/kong/includes/kubernetes.conf <<-'EOF'
-                            stream {
-                                upstream kubernetes-api-cluster {
-                                    {{range .MasterIPs}}server {{.}}:6443;
-                                    {{end}} 
-                                }
+                            upstream kubernetes-api-cluster {
+                                {{range .MasterIPs}}server {{.}}:6443;
+                                {{end}} 
+                            }
 
-                                server { 
-                                    listen 6443;
-                                    proxy_pass kubernetes-api-cluster; 
-                                }
+                            server { 
+                                listen 6443;
+                                proxy_pass kubernetes-api-cluster; 
                             }
                             EOF
                             sfReverseProxyReload
+                            exit 0
 
                     cp1-init:
                         targets:
@@ -274,7 +272,7 @@ feature:
                             kubernetesVersion: stable
                             controlPlaneEndpoint: "{{.GatewayIP}}:6443"
                             networking:
-                                podSubnet: 10.96.0.0/16
+                                podSubnet: 10.244.0.0/16
                             EOF
 
                             sfRetry 5m 5 kubeadm config images pull || exit 197
@@ -289,6 +287,7 @@ feature:
 
                             # execute init_cluster_admin_kube.sh on the current master
                             bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || exit 199
+                            # Starting from here, any kubectl command must be changed to sfKubectl
 
                             # Push control-plane join command to all the other masters
                             echo $cp_join_cmd | head -1 >${SF_TMPDIR}/cp_join_cmd.sh
@@ -303,9 +302,9 @@ feature:
                             sfDropzoneClean
 
                             # waits availability of key pods
-                            sfRetry 5m 10 sh -c "kubectl get -n kube-system pod kube-apiserver-{{.Hostname}} -o {{ "'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}'" }} == \"True\"" || exit 203
-                            sfRetry 5m 10 sh -c "kubectl get -n kube-system pod kube-controller-manager-{{.Hostname}} -o {{ "'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}'" }} == \"True\"" || exit 204
-                            sfRetry 5m 10 sh -c "kubectl get -n kube-system pod kube-scheduler-{{.Hostname}} -o {{ "'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}'" }} == \"True\"" || exit 205
+                            sfRetry 5m 10 sh -c "sfKubectl get -n kube-system pod kube-apiserver-{{.Hostname}} -o {{ "'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}'" }} == \"True\"" || exit 203
+                            sfRetry 5m 10 sh -c "sfKubectl get -n kube-system pod kube-controller-manager-{{.Hostname}} -o {{ "'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}'" }} == \"True\"" || exit 204
+                            sfRetry 5m 10 sh -c "sfKubectl get -n kube-system pod kube-scheduler-{{.Hostname}} -o {{ "'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}'" }} == \"True\"" || exit 205
 
                             touch /etc/kubernetes/.joined
                             echo "init done"
@@ -315,12 +314,21 @@ feature:
                         targets:
                             masters: one
                         run: |
-                            kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml || exit 206
+                            case {{.CNI}} in
+                                flannel)
+                                    sfKubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml || exit 206
 
-                            sfFirewallAdd --zone=trusted --add-interface=flannel.1
-                            sfFirewallAdd --zone=trusted  --add-interface=cni0
-                            sfFirewallReload
-
+                                    sfFirewallAdd --zone=trusted --add-interface=flannel.1
+                                    sfFirewallAdd --zone=trusted --add-interface=cni0
+                                    sfFirewallReload
+                                    ;;
+                                canal)
+                                    # Untested yet...
+                                    sfKubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/canal/canal.yaml || exit 207
+                                    sfFirewallAdd --zone=trusted --add-interface=cni0
+                                    sfFirewallReload
+                                    ;;
+                            esac
                             exit 0
 
                     cpx-init:
@@ -330,23 +338,31 @@ feature:
                             # Don't try to init a kubernetes cluster already running
                             [ -f /etc/kubernetes/.joined ] && exit 0
 
-                            sfDropzonePop "*" ${SF_TMPDIR} || exit 207
+                            sfDropzonePop "*" ${SF_TMPDIR} || exit 208
                             sfDropzoneClean
 
-                            [ ! -f ${SF_TMPDIR}/cp_join_cmd.sh ] && exit 208
-                            bash ${SF_TMPDIR}/cp_join_cmd.sh || exit 209
-                            [ ! -f ${SF_TMPDIR}/init_cluster_admin_kube.sh ] || exit 210
-                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || exit 211
+                            [ ! -f ${SF_TMPDIR}/cp_join_cmd.sh ] && exit 209
+                            bash ${SF_TMPDIR}/cp_join_cmd.sh || exit 210
+                            [ ! -f ${SF_TMPDIR}/init_cluster_admin_kube.sh ] && exit 211
+                            bash ${SF_TMPDIR}/init_cluster_admin_kube.sh || exit 212
 
                             # waits availability of key pods
-                            sfRetry 5m 10 sh -c "kubectl get -n kube-system pod kube-apiserver-{{.Hostname}} -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') == \"True\"" || exit 212
-                            sfRetry 5m 10 sh -c "kubectl get -n kube-system pod kube-controller-manager-{{.Hostname}} -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') == \"True\"" || exit 213
-                            sfRetry 5m 10 sh -c "kubectl get -n kube-system pod kube-scheduler-{{.Hostname}} -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') == \"True\"" || exit 214
+                            sfRetry 5m 10 sh -c "sfKubectl get -n kube-system pod kube-apiserver-{{.Hostname}} -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') == \"True\"" || exit 213
+                            sfRetry 5m 10 sh -c "sfKubectl get -n kube-system pod kube-controller-manager-{{.Hostname}} -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') == \"True\"" || exit 214
+                            sfRetry 5m 10 sh -c "sfKubectl get -n kube-system pod kube-scheduler-{{.Hostname}} -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') == \"True\"" || exit 215
 
                             # Configure firewall
-                            sfFirewallAdd --zone=trusted --add-interface=flannel.1
-                            sfFirewallAdd --zone=trusted --add-interface=cni0
-                            sfFirewallReload
+                            case {{.CNI}} in
+                                flannel)
+                                    sfFirewallAdd --zone=trusted --add-interface=flannel.1
+                                    sfFirewallAdd --zone=trusted --add-interface=cni0
+                                    sfFirewallReload
+                                    ;;
+                                canal)
+                                    sfFirewallAdd --zone=trusted --add-interface=cni0
+                                    sfFirewallReload
+                                    ;;
+                            esac
 
                             exit 0
 
@@ -365,18 +381,20 @@ feature:
                                 MASTERIP=$m
                                 break
                             done
-                            [ -z "$MASTERIP" ] && echo "failed to find available master to register with. Aborted." && exit 215
-                            eval $NODE_JOIN_CMD || exit 216
+                            [ -z "$MASTERIP" ] && echo "failed to find available master to register with. Aborted." && exit 216
+                            eval $NODE_JOIN_CMD || exit 217
                             touch /etc/kubernetes/.joined
+                            exit 0
 
                     final:
                         targets:
                             masters: one
                         run: |
                             # Allows pods to start on master if there is only one master or if it's explicitely requested
-                            [ "{{.Complexity}}" = "small" -o "{{.AllowPodsOnMasters}}" = "true" ] && sfKubectl taint nodes --all node-role.kubernetes.io/master-
+                            [ "{{.ClusterComplexity}}" = "small" -o "{{.AllowPodsOnMasters}}" = "true" ] && sfKubectl taint nodes --all node-role.kubernetes.io/master-
                             # adds Kubernetes Dashboard
-                            sfRetry 3m 5 sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml || exit 217
+                            sfRetry 3m 5 sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml || exit 218
+                            exit 0
 
             remove:
                 pace: node,reset,reverseproxy,clean
@@ -385,14 +403,14 @@ feature:
                         targets:
                             masters: one
                         run: |
-                            kubectl drain {{.Hostname}} --delete-local-data --force --ignore-daemonsets
-                            kubectl delete node {{.Hostname}}
+                            sfKubectl drain {{.Hostname}} --delete-local-data --force --ignore-daemonsets
+                            sfKubectl delete node {{.Hostname}}
 
                     reverseproxy:
                         targets:
                             gateways: all
                         run: |
-                            rm /opt/safescale/etc/kong/kubernetes.conf
+                            rm -f /opt/safescale/etc/kong/includes/kubernetes.conf
                             sfReverseProxyReload
 
                     reset:
@@ -407,7 +425,6 @@ feature:
                             privateNodes: all
                             publicNodes: all
                         run: |
-                            kubeadm reset &>/dev/null
                             case $LINUX_KIND in
                                 debian|ubuntu)
                                     sfApt purge -y kubectl kubeadm kubelet || exit 192
