If new kubernetes dashboard version fails, use the previous non-beta version

diff --git a/features/kubernetes.yml b/features/kubernetes.yml
--- a/features/kubernetes.yml
+++ b/features/kubernetes.yml
@@ -429,9 +429,11 @@ feature:
                             # adds Kubernetes Dashboard
                             if [ "{{.Dashboard}}" = "true" ]; then
                                 if curl --output /dev/null --silent --head --fail "https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml"; then
-                                    sfRetry 3m 5 sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || fail 222 "Unable to install kubernetes dashboard"
+                                    sfRetry 3m 5 sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || fail 222 "Unable to install kubernetes dashboard version $(sfGithubLastRelease)"
                                 else
-                                    fail 222 "Wrong url for the Kubernetes Dashboard"
+                                    if curl --output /dev/null --silent --head --fail "https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastNotBetaRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml"; then
+                                        sfRetry 3m 5 sfKubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/$(sfGithubLastNotBetaRelease kubernetes dashboard)/src/deploy/recommended/kubernetes-dashboard.yaml || fail 222 "Unable to install kubernetes dashboard version $(sfGithubLastNotBetaRelease)"
+                                    fi
                                 fi
                             fi
 
