Changes in features
- Renamed exit to sfFail

diff --git a/features/logstash.yml b/features/logstash.yml
--- a/features/logstash.yml
+++ b/features/logstash.yml
@@ -37,9 +37,19 @@ feature:
                             masters: all
                             nodes: no
                         run: |
+<<<<<<< refs/remotes/origin/develop
                             [ -d ${SF_ETCDIR}/logstash ] || exit 192
                             docker image ls {{ "--format '{{.Repository}}:{{.Tag}}'" }} | grep 'logstash:7.1.1' &>/dev/null || exit 193
                             exit 0
+||||||| ancestor
+                            [ -d ${SF_ETCDIR}/logstash ] || fail 192
+                            docker image ls {{ "--format '{{.Repository}}:{{.Tag}}'" }} | grep 'logstash:7.1.1' &>/dev/null || fail 193
+                            exit 0
+=======
+                            [ -d ${SF_ETCDIR}/logstash ] || sfFail 192
+                            docker image ls {{ "--format '{{.Repository}}:{{.Tag}}'" }} | grep 'logstash:7.1.1' &>/dev/null || sfFail 193
+                            sfFail 0
+>>>>>>> Changes in features
 
             add:
                 pace: image,config,start,ready
@@ -130,7 +140,7 @@ feature:
                                         - ${SF_ETCDIR}/logstash/pipeline/:/usr/share/logstash/pipeline/:ro
                                     restart: always
                             EOF
-                            exit 0
+                            sfFail 0
 
                     start:
                         targets:
@@ -172,7 +182,13 @@ feature:
                             {{ else }}
                             OPTIONS=
                             {{ end }}
+<<<<<<< refs/remotes/origin/develop
                             docker-compose -f ${SF_ETCDIR}/logstash/docker-compose.yml $OPTIONS rm --stop -v --force || exit 192
+||||||| ancestor
+                            docker-compose -f ${SF_ETCDIR}/logstash/docker-compose.yml $OPTIONS rm --stop -v --force || fail 192
+=======
+                            docker-compose -f ${SF_ETCDIR}/logstash/docker-compose.yml $OPTIONS rm --stop -v --force || sfFail 192
+>>>>>>> Changes in features
 
                     remove:
                         targets:
@@ -182,6 +198,6 @@ feature:
                         run: |
                             docker image rm -f logstash:7.1.1
                             rm -rf ${SF_ETCDIR}/logstash
-                            exit 0
+                            sfFail 0
 
 ...
