Change in feature postgresql4platform
- fixed a misuse of sfFail in remote script

diff --git a/features/postgresql4platform.yml b/features/postgresql4platform.yml
--- a/features/postgresql4platform.yml
+++ b/features/postgresql4platform.yml
@@ -432,20 +432,20 @@ feature:
                         run: |
                             mkdir -p ${SF_ETCDIR}/postgresql4platform/build/pgpool
 
-                            cat >${SF_ETCDIR}/postgresql4platform/build/pgpool/update_password.sh <<-EOF
+                            cat >${SF_ETCDIR}/postgresql4platform/build/pgpool/update_password.sh <<-'EOF'
                             #!/bin/bash
-                            [ \$# -ne 2 ] && echo "invalid parameters" && sfFail 1
+                            [ $# -ne 2 ] && echo "invalid parameters" && exit 1
 
-                            USERNAME=\$1
-                            PASSWORD="\$2"
+                            USERNAME=$1
+                            PASSWORD="$2"
 
-                            grep -v "^\${USERNAME}:" /etc/postgresql/pool_passwd | grep -e ".*:md5.*" >/tmp/pool_passwd.new
+                            grep -v "^${USERNAME}:" /etc/postgresql/pool_passwd | grep -e ".*:md5.*" >/tmp/pool_passwd.new
                             >/etc/postgresql/pool_passwd
 
                             cat /tmp/pool_passwd.new >>/etc/postgresql/pool_passwd
                             rm /tmp/pool_passwd.new
-                            pg_md5 --config-file=/etc/postgresql/pgpool.conf -m --username=\$USERNAME "\$PASSWORD"
-                            exit \$?
+                            pg_md5 --config-file=/etc/postgresql/pgpool.conf -m --username=$USERNAME "$PASSWORD"
+                            exit $?
                             EOF
 
                             cat >${SF_ETCDIR}/postgresql4platform/build/pgpool/my-docker-entrypoint.sh <<-EOF
