Changes in features
- Renamed exit to sfFail

diff --git a/features/postgresql4platform.yml b/features/postgresql4platform.yml
--- a/features/postgresql4platform.yml
+++ b/features/postgresql4platform.yml
@@ -35,8 +35,8 @@ feature:
                             masters: any
                             nodes: no
                         run: |
-                            sfDoesDockerRunStack postgresql4platform || exit 192
-                            exit 0
+                            sfDoesDockerRunStack postgresql4platform || sfFail 192
+                            sfFail 0
 
             add:
                 pace: network,pgsql-cfg,pgsql-img,pgpool-cfg,pgpool-img,reverseproxy,secrets,stack,start
@@ -137,7 +137,7 @@ feature:
                             service_reload_command='pg_ctl -D /var/lib/postgresql/data reload'
                             EOF
                             chown 70:safescale ${SF_ETCDIR}/postgresql4platform/repmgr.conf
-                            exit 0
+                            sfFail 0
 
                     pgpool-cfg:
                         targets:
@@ -161,8 +161,8 @@ feature:
                             log_destination = 'stderr'
                             print_timestamp = on
 
-                            failover_on_backend_error = on
-                            failover_command = '/bin/true'
+                            exitover_on_backend_error = on
+                            exitover_command = '/bin/true'
 
                             memory_cache_enabled = on
                             memqcache_method = 'shmem'
@@ -197,12 +197,12 @@ feature:
                             backend_port${i} = 5432
                             backend_weight${i} = 1
                             backend_data_directory${i} = '/var/lib/postgresql/data'
-                            backend_flag${i} = 'ALLOW_TO_FAILOVER'
+                            backend_flag${i} = 'ALLOW_TO_exitOVER'
                             EOF
                             done
                             chown 70:safescale ${SF_ETCDIR}/postgresql4platform/pgpool.conf.template
                             chmod u+rw-x,g+r-wx,o-rwx ${SF_ETCDIR}/postgresql4platform/pgpool.conf.template
-                            exit 0
+                            sfFail 0
 
                     pgsql-img:
                         targets:
@@ -266,7 +266,10 @@ feature:
                                 update_postgresql_conf
                                 update_pghba_conf
                                 pg_ctl start &>/dev/null && wait_for_local_postgres 60
-                                [ \$? -ne 0 ] && echo "Failed." && exit 1
+                                [ \$? -ne 0 ] && echo "Failed." && sfFail 1
+                                op=-1
+                                pg_ctl start &>/dev/null && wait_for_local_postgres 60 && op=\$?
+                                [ \$op -ne 0 ] && echo "Failed." && sfFail 1
                                 echo OK
 
                                 # Checking if repmgr needs to be initialized
@@ -284,16 +287,16 @@ feature:
                                     echo done
 
                                     echo -n "registering host as primary postgresql instance... "
-                                    repmgr --config-file=/etc/postgresql/repmgr.conf primary register
-                                    [ \$? -ne 0 ] && echo "Failed." && exit 2
-                                    echo done
+                                    op=-1
+                                    repmgr --config-file=/etc/postgresql/repmgr.conf primary register && op=\$?
+                                    [ \$op -ne 0 ] && echo "Failed." && sfFail 2
                                 fi
                                 pg_ctl stop -m fast &>/dev/null
                             else
                                 # We are on a slave
                                 echo -n "Waiting postgresql master is ready... "
                                 wait_for_dbmaster 60
-                                [ \$? -ne 0 ] && echo Failed && exit 3
+                                [ \$? -ne 0 ] && echo Failed && sfFail 3
                                 echo OK
                                 registered=\$(psql -qAt -h "\$REPMGR_PRIMARY_HOST" -U repmgr repmgr -c "SELECT 1 FROM repmgr.nodes WHERE node_id=\${nodeid}")
                                 if [ "\$registered" != "1" ]; then
@@ -304,17 +307,19 @@ feature:
                                     set +x
                                     update_postgresql_conf
                                     update_pghba_conf
-                                    pg_ctl start &>/dev/stdout && wait_for_local_postgres 60
-                                    [ \$? -ne 0 ] && echo "Failed to start postgresql instance." && exit 4
+                                    op=-1
+                                    pg_ctl start &>/dev/stdout && wait_for_local_postgres 60 && op=\$?
+                                    [ \$op -ne 0 ] && echo "exited to start postgresql instance." && sfFail 4
                                     echo -n "Registering postgresql instance as hot-standby... "
-                                    repmgr --config-file=/etc/postgresql/repmgr.conf --host="\$REPMGR_PRIMARY_HOST" --username=repmgr --dbname=repmgr standby register
-                                    [ \$? -ne 0 ] && echo "Failed." && exit 5
+                                    op=-1
+                                    repmgr --config-file=/etc/postgresql/repmgr.conf --host="\$REPMGR_PRIMARY_HOST" --username=repmgr --dbname=repmgr standby register && op=\$?
+                                    [ \$op -ne 0 ] && echo "exited." && sfFail 5
                                     echo done
                                 fi
                             fi
                             echo done
 
-                            # TODO: find a way to mitigate restarts from failure
+                            # TODO: find a way to mitigate restarts from exiture
                             # - select conninfo,type,active from repmgr.nodes then consolidate results
                             # - If current instance believes it's a master, and there is another master from the results with more active=t,
                             #   stop the current instance and follow the other master. pg_rewind needed ?
@@ -352,7 +357,7 @@ feature:
                             #if [ \$designated_master_count -lt 1 ]; then
                             #    echo "Postgresql cluster is in inconsistent state:"
                             #    echo "no primary instance registered!"
-                            #    exit 40
+                            #    sfFail 40
                             #fi
                             ## A new loop to find if there is at least 2 dbhosts with the same count of master role (which can't be
                             ## automatically mitigated)
@@ -412,8 +417,8 @@ feature:
                             CMD ["postgres"]
                             EOF
 
-                            docker build --network host -t pgsql4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgsql || exit 192
-                            exit 0
+                            docker build --network host -t pgsql4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgsql || sfFail 192
+                            sfFail 0
 
                     pgpool-img:
                         targets:
@@ -423,7 +428,7 @@ feature:
 
                             cat >${SF_ETCDIR}/postgresql4platform/build/pgpool/update_password.sh <<-EOF
                             #!/bin/bash
-                            [ \$# -ne 2 ] && echo "invalid parameters" && exit 1
+                            [ \$# -ne 2 ] && echo "invalid parameters" && sfFail 1
 
                             USERNAME=\$1
                             PASSWORD="\$2"
@@ -433,7 +438,7 @@ feature:
                             cat /tmp/pool_passwd.new >>/etc/postgresql/pool_passwd
                             rm /tmp/pool_passwd.new
                             pg_md5 --config-file=/etc/postgresql/pgpool.conf -m --username=\$USERNAME "\$PASSWORD"
-                            exit \$?
+                            sfFail \$?
                             EOF
 
                             cat >${SF_ETCDIR}/postgresql4platform/build/pgpool/my-docker-entrypoint.sh <<-EOF
@@ -477,8 +482,8 @@ feature:
                             ENTRYPOINT ["/sbin/tini", "--", "/my-docker-entrypoint.sh"]
                             EOF
 
-                            docker build --network host -t pgpool4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgpool || exit 192
-                            exit 0
+                            docker build --network host -t pgpool4platform:latest ${SF_ETCDIR}/postgresql4platform/build/pgpool || sfFail 192
+                            sfFail 0
 
                     stack:
                         targets:
@@ -554,7 +559,7 @@ feature:
                                             constraints:
                                                 - node.hostname == ${HOSTNAME_RADIX}-1
                                         restart_policy:
-                                            condition: on-failure
+                                            condition: on-exiture
                                             delay: 5s
                                             max_attempts: 3
                                             window: 120s
@@ -605,7 +610,7 @@ feature:
                                             constraints:
                                                 - node.hostname == ${SLAVE_HOST}
                                         restart_policy:
-                                            condition: on-failure
+                                            condition: on-exiture
                                             delay: 5s
                                             max_attempts: 3
                                             window: 120s
@@ -638,7 +643,7 @@ feature:
                                             constraints:
                                                 - node.labels.safescale.host.role == master
                                         restart_policy:
-                                            condition: on-failure
+                                            condition: on-exiture
                                             delay: 5s
                                             max_attempts: 3
                                             window: 120s
@@ -652,7 +657,7 @@ feature:
                             EOF
                             fi
                                 chmod go-rwx ${SF_ETCDIR}/postgresql4platform/stack.yml
-                            exit 0
+                            sfFail 0
 
                     reverseproxy:
                         targets:
@@ -663,7 +668,7 @@ feature:
                             elif [ -d ${SF_ETCDIR}/kong4gateway ]; then
                                 TARGET_DIR=${SF_ETCDIR}/kong4gateway
                             fi
-                            [ -z "${TARGET_DIR+x}" ] && exit 197
+                            [ -z "${TARGET_DIR+x}" ] && sfFail 197
 
                             cat >${TARGET_DIR}/includes/postgresql4platform.conf <<-'EOF'
                             upstream postgresql4platform {
@@ -677,38 +682,38 @@ feature:
                             }
                             EOF
                             sfReverseProxyReload
-                            exit 0
+                            sfFail 0
 
                     network:
                         targets:
                             masters: any
                         run: |
                             if ! docker network list --filter 'name=postgresql4platform_net' | grep postgresql4platform_net; then
-                                docker network create --attachable -d overlay --scope swarm postgresql4platform_net || exit 193
+                                docker network create --attachable -d overlay --scope swarm postgresql4platform_net || sfFail 193
                             fi
-                            exit 0
+                            sfFail 0
 
                     secrets:
                         targets:
                             masters: any
                         run: |
                             if docker secret inspect safescale.postgresql.password.password.postgres &>/dev/null; then
-                                docker secret rm safescale.postgresql.password.postgres || exit 193
+                                docker secret rm safescale.postgresql.password.postgres || sfFail 193
                             fi
-                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.postgres - || exit 194
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.postgres - || sfFail 194
                             if docker secret inspect safescale.postgresql.password.repmgr &>/dev/null; then
-                                docker secret rm safescale.postgresql.password.repmgr || exit 195
+                                docker secret rm safescale.postgresql.password.repmgr || sfFail 195
                             fi
-                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.repmgr - || exit 196
-                            exit 0
+                            echo -n "$(sfRandomString 16 "[:alnum:]")" | docker secret create safescale.postgresql.password.repmgr - || sfFail 196
+                            sfFail 0
 
                     start:
                         targets:
                             masters: any
                         run: |
-                            docker stack deploy -c ${SF_ETCDIR}/postgresql4platform/stack.yml postgresql4platform || exit 197
-                            sfRetry 5m 5 sfDoesDockerRunStack postgresql4platform || exit 1978
-                            exit 0
+                            docker stack deploy -c ${SF_ETCDIR}/postgresql4platform/stack.yml postgresql4platform || sfFail 197
+                            sfRetry 5m 5 sfDoesDockerRunStack postgresql4platform || sfFail 198
+                            sfFail 0
 
             remove:
                 pace: stack,cleanup
@@ -718,9 +723,9 @@ feature:
                             masters: any
                         run: |
                             if [ -f ${SF_ETCDIR}/postgresql4platform/stack.yml ]; then
-                                docker stack rm postgresql4platform || exit 192
+                                docker stack rm postgresql4platform || sfFail 192
                             fi
-                            exit 0
+                            sfFail 0
 
                     cleanup:
                         targets:
@@ -734,6 +739,6 @@ feature:
                             if [ "${PURGE_ON_REMOVAL,,}" = "yes" -o "${PURGE_ON_REMOVAL,,}" = "true" ]; then
                                 rm -rf ${SF_ETCDIR}/postgresql4platform ${SF_VARDIR}/postgresql4platform
                             fi
-                            exit 0
+                            sfFail 0
 
 ...
